<a href="https://colab.research.google.com/github/gautamkr1876/AIML_ClassNotes/blob/main/Data%20Foundation/G%20-Amazon%20sales%20data%20analysis%201/Amazon_sales_data_analysis_1.ipynb" target="_blank">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Amazon sales data analysis 1

---

## <span style="color: skyblue;"> Agenda </span>

* Working with Both Rows and Columns
* Handling Duplicate Records in a DataFrame
* Pandas Built-In Operations - Aggregate Functions
* Sorting Values in Pandas
* General discussion and loading the dataset
* Merging dataframes
* Applying functions with `.apply()`
* Grouping in Pandas

> <span style="color: red;"> **Note:** </span> <span style="background-color: Blue;">[Link](https://colab.research.google.com/drive/1EG-NsxWCPdfTo1T9yFqKV3wfKVWNHhor?usp=sharing)</span> of the colab notebook used in the lecture and to be shared with learners.

# Working with Both Rows and Columns


When analyzing data, you often need to work with both rows and columns simultaneously. Pandas provides powerful tools for selecting, slicing, and filtering data across multiple axes.

**Key Tools for Selection**:
1. **`.iloc`**: Select rows and columns by integer position.
2. **`.loc`**: Select rows and columns by labels.

> [Interactive]: Explore how pandas indexing works step by step before diving into the code:
[Pandas Indexing Visualizer](https://aiml-v-izs.vercel.app/v/az-j9x3r6t1/pd-indexing)

## <span style="color: skyblue;"> Using `.iloc` for Rows and Columns </span>

The `.iloc` method allows you to:
1. Select specific rows and columns by their integer indices.
2. Slice rows and columns together.

#### Example: Selecting Specific Rows and Columns

We will import our dataset that we exported in the last lecture: https://drive.google.com/file/d/1i-tHRLBGkq_X2BHrJtiRNMLA4AZCCzZc/view?usp=drive_link

In [ ]:
!gdown 1i-tHRLBGkq_X2BHrJtiRNMLA4AZCCzZc

Downloading...
From (original): https://drive.google.com/uc?id=1i-tHRLBGkq_X2BHrJtiRNMLA4AZCCzZc
From (redirected): https://drive.google.com/uc?id=1i-tHRLBGkq_X2BHrJtiRNMLA4AZCCzZc&confirm=t&uuid=bab03dc4-204b-436f-859f-fa6c99aafa60
To: /content/lec_4_df_zomato.csv
100% 486M/486M [00:06<00:00, 70.7MB/s]

In [ ]:
import pandas as pd
df = pd.read_csv("lec_4_df_zomato.csv")

In [ ]:
# Select the first two rows and the first two columns
df.iloc[0:2, 0:2]

,url,address
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ..."
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ..."

In [ ]:
# Select the last two rows and the last column
df.iloc[-2:, -1]

23191    False
23192     True
Name: is_good, dtype: bool

## <span style="color: skyblue;"> Using .iloc to Modify Data ( Would want to use the same dataset instead of creating a new one) </span>

In [ ]:
# For restaurants R2 and R3 on Zomato, update their number of votes and
# ratings to reflect recent changes in customer engagement and feedback.
# How can we modify the DataFrame to apply these updates at once?


# Example DataFrame
data = {
    "Restaurant": ["R1", "R2", "R3", "R4"],
    "Votes": [120, 240, 150, 80],
    "Rating": [4.1, 4.5, 3.9, 4.0]
}

sample_df = pd.DataFrame(data)

# Assigning new values to multiple rows and columns
sample_df.iloc[1:3, 1:3] = [[300, 4.7], [180, 4.2]]

print("DataFrame after modifying rows and columns:")
print(sample_df)

DataFrame after modifying rows and columns:
  Restaurant  Votes  Rating
0         R1    120     4.1
1         R2    300     4.7
2         R3    180     4.2
3         R4     80     4.0

## <span style="color: skyblue;"> Using .loc to Select Rows and Columns </span>

The `.loc` method allows you to:
- Filter rows based on conditions.
- Update specific rows and columns by labels.


<span style=" color: red;">Narrative:</span> Your manager/team wants you to flag a few restaurants as 1, 0, or -1 based on customer/delivery partner feedback

In [ ]:
# Zomato wants to mark all restaurants with an initial flag to track them for future analysis or promotions.
# How can we add a new column flag and set it to 1 for all restaurants in the DataFrame?

#create a new column to keep track of flags - initially set it as 1 for all restaurants
df['flag'] = 1

In [ ]:
df

,url,address,name,online_order,book_table,Ratings,Total_Votes,phone,location,rest_type,...,cuisines,cost_for_two,reviews_list,menu_item,listed_in(type),listed_in(city),only_rating,cost_for_one,is_good,flag
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,...,"North Indian, Mughlai, Chinese",800.0,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari,4.1,400.0,True,1
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,...,"Chinese, North Indian, Thai",800.0,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari,4.1,400.0,True,1
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining",...,"Cafe, Mexican, Italian",800.0,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari,3.8,400.0,False,1
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,...,"South Indian, North Indian",300.0,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari,3.7,150.0,False,1
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,...,"North Indian, Rajasthani",600.0,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari,3.8,300.0,False,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23188,https://www.zomato.com/bangalore/izakaya-gastr...,"2nd Floor, Iona, Virginia Mall, Whitefield Mai...",Izakaya Gastro Pub,Yes,Yes,3.8 /5,128,+91 7625087121\n+91 8050587483,Whitefield,"Bar, Casual Dining",...,"North Indian, Continental, Mediterranean",1200.0,"[('Rated 3.0', ""RATED\n Nice place to hangout...",[],Pubs and bars,Whitefield,3.8,600.0,False,1
23189,https://www.zomato.com/bangalore/m-bar-bengalu...,"Bengaluru Marriott Hotel, 75, 8th Road, EPIP A...",M Bar - Bengaluru Marriott Hotel Whitefield,No,No,3.9 /5,77,080 49435000,Whitefield,"Fine Dining, Bar",...,Finger Food,2000.0,"[('Rated 4.0', 'RATED\n Went there post dinne...",[],Pubs and bars,Whitefield,3.9,1000.0,False,1
23190,https://www.zomato.com/bangalore/keys-cafe-key...,"Keys Hotel, 6, 1st Phase Industrial Area, Near...",Keys Cafe - Keys Hotel,No,No,2.8 /5,161,080 39451000\n+91 8884038484,Whitefield,"Casual Dining, Bar",...,"Chinese, Continental, North Indian",1200.0,"[('Rated 3.0', 'RATED\n Place is good not tha...",[],Pubs and bars,Whitefield,2.8,600.0,False,1
23191,https://www.zomato.com/bangalore/bhagini-2-whi...,"139/C1, Next To GR Tech Park, Pattandur Agraha...",Bhagini,No,No,2.5 /5,81,080 65951222,Whitefield,"Casual Dining, Bar",...,"Andhra, South Indian, Chinese, North Indian",800.0,"[('Rated 4.0', 'RATED\n A fine place to chill...",[],Pubs and bars,Whitefield,2.5,400.0,False,1
23192,https://www.zomato.com/bangalore/chime-sherato...,Sheraton Grand Bengaluru Whitefield Hotel & Co...,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,236,080 49652769,"ITPL Main Road, Whitefield",Bar,...,Finger Food,2500.0,"[('Rated 4.0', 'RATED\n Nice and friendly pla...",[],Pubs and bars,Whitefield,4.3,1250.0,True,1

In [ ]:
# Setting 'Restaurant' as the index
df_explicit = df.set_index("name")

# Select specific rows ('R2' and 'R3') and specific columns ('flag')
print(df_explicit.loc[["Jalsa", "Grand Village"], ["flag"]])
print("==="*10)

# Updating the 'flag' for restaurant 'Jalsa.'
df_explicit.loc["Jalsa", "flag"] = 0
print("Updated DataFrame:")
df_explicit

               flag
name
Jalsa             1
Jalsa             1
Jalsa             1
Jalsa             1
Jalsa             1
Jalsa             1
Jalsa             1
Jalsa             1
Jalsa             1
Jalsa             1
Jalsa             1
Grand Village     1
Grand Village     1
Grand Village     1
Grand Village     1
==============================
Updated DataFrame:

,url,address,online_order,book_table,Ratings,Total_Votes,phone,location,rest_type,dish_liked,cuisines,cost_for_two,reviews_list,menu_item,listed_in(type),listed_in(city),only_rating,cost_for_one,is_good,flag
name,,,,,,,,,,,,,,,,,,,,
Jalsa,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800.0,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari,4.1,400.0,True,0
Spice Elephant,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800.0,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari,4.1,400.0,True,1
San Churro Cafe,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800.0,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari,3.8,400.0,False,1
Addhuri Udupi Bhojana,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300.0,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari,3.7,150.0,False,1
Grand Village,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600.0,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari,3.8,300.0,False,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Izakaya Gastro Pub,https://www.zomato.com/bangalore/izakaya-gastr...,"2nd Floor, Iona, Virginia Mall, Whitefield Mai...",Yes,Yes,3.8 /5,128,+91 7625087121\n+91 8050587483,Whitefield,"Bar, Casual Dining","Beer, Chicken Guntur, Paneer Tikka, Fish, Nood...","North Indian, Continental, Mediterranean",1200.0,"[('Rated 3.0', ""RATED\n Nice place to hangout...",[],Pubs and bars,Whitefield,3.8,600.0,False,1
M Bar - Bengaluru Marriott Hotel Whitefield,https://www.zomato.com/bangalore/m-bar-bengalu...,"Bengaluru Marriott Hotel, 75, 8th Road, EPIP A...",No,No,3.9 /5,77,080 49435000,Whitefield,"Fine Dining, Bar",Rooftop Ambience,Finger Food,2000.0,"[('Rated 4.0', 'RATED\n Went there post dinne...",[],Pubs and bars,Whitefield,3.9,1000.0,False,1
Keys Cafe - Keys Hotel,https://www.zomato.com/bangalore/keys-cafe-key...,"Keys Hotel, 6, 1st Phase Industrial Area, Near...",No,No,2.8 /5,161,080 39451000\n+91 8884038484,Whitefield,"Casual Dining, Bar","Salads, Coffee, Breakfast Buffet, Halwa, Chick...","Chinese, Continental, North Indian",1200.0,"[('Rated 3.0', 'RATED\n Place is good not tha...",[],Pubs and bars,Whitefield,2.8,600.0,False,1
Bhagini,https://www.zomato.com/bangalore/bhagini-2-whi...,"139/C1, Next To GR Tech Park, Pattandur Agraha...",No,No,2.5 /5,81,080 65951222,Whitefield,"Casual Dining, Bar","Biryani, Andhra Meal","Andhra, South Indian, Chinese, North Indian",800.0,"[('Rated 4.0', 'RATED\n A fine place to chill...",[],Pubs and bars,Whitefield,2.5,400.0,False,1
Chime - Sheraton Grand Bengaluru Whitefield Hotel &...,https://www.zomato.com/bangalore/chime-sherato...,Sheraton Grand Bengaluru Whitefield Hotel & Co...,No,Yes,4.3 /5,236,080 49652769,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,2500.0,"[('Rated 4.0', 'RATED\n Nice and friendly pla...",[],Pubs and bars,Whitefield,4.3,1250.0,True,1

## <span style="color: skyblue;"> Using .loc for Conditional Updates </span>

<span style=" color: red;">Narrative:</span> You also receive information to flag restaurants with ratings less than 3 as -1 and between 3 and 4 as 0

In [ ]:
# Zomato wants to identify underperforming restaurants with ratings below 3 and mark them for review.
# How can we update the flag column to -1 for all restaurants where only_rating is less than 3?

# Update 'Rating' for all restaurants with 'Votes' greater than 200
df_explicit.loc[df_explicit["only_rating"] < 3, "flag"] = -1

## <span style="color: skyblue;"> Combining DataFrames with `concat.` </span>

The `concat` function allows you to combine multiple DataFrames:
1. **Row-wise Concatenation**: Add rows from another DataFrame.
2. **Column-wise Concatenation**: Add new columns from another DataFrame.

**1. Row-wise Concatenation**

You can stack two DataFrames vertically to combine their rows:

In [ ]:
# How can Zomato's data team combine a new set of restaurant data (e.g.,
# new Bangalore restaurants) Can the existing dataset be used to create a unified DataFrame for comprehensive analysis?


# Creating a second DataFrame
data2 = {
    "Restaurant": ["R5", "R6"],
    "Votes": [90, 110],
    "Rating": [3.8, 4.3]
}

df2 = pd.DataFrame(data2)

# Concatenating row-wise
combined_df = pd.concat([sample_df, df2], ignore_index=True)
print("Combined DataFrame (Row-wise):")
print(combined_df)

Combined DataFrame (Row-wise):
  Restaurant  Votes  Rating
0         R1    120     4.1
1         R2    300     4.7
2         R3    180     4.2
3         R4     80     4.0
4         R5     90     3.8
5         R6    110     4.3

### <span style=color:orange> Zomato Business Context:</span>

- Row-wise concatenation allows Zomato to append new restaurant data (e.g., newly onboarded restaurants in Bangalore) to the existing dataset, ensuring the dataset stays up-to-date for user recommendations.
- Using ignore_index=True creates a new numerical index, simplifying analysis by maintaining a clean, sequential order for all restaurants.
- This approach helps Zomato integrate data from multiple sources (e.g., new restaurant listings or partner updates), supporting comprehensive market analysis and personalized dining suggestions.

**2. Column-wise Concatenation**

You can stack DataFrames side-by-side to add new columns:

In [ ]:
# Creating a DataFrame with new columns
new_columns = {
    "Delivery Time (mins)": [30, 25, 35, 20, 40, 28]
}

df_new_cols = pd.DataFrame(new_columns)

# Concatenating column-wise
final_df = pd.concat([combined_df, df_new_cols], axis=1)
print("Final DataFrame (Column-wise):")
final_df

Final DataFrame (Column-wise):

  Restaurant  Votes  Rating  Delivery Time (mins)
0         R1    120     4.1                    30
1         R2    300     4.7                    25
2         R3    180     4.2                    35
3         R4     80     4.0                    20
4         R5     90     3.8                    40
5         R6    110     4.3                    28

### <span style=color:orange> Zomato Business Context:</span>

- Adding a Delivery Time (mins) column enhances the dataset by providing insights into delivery efficiency, a key factor for Zomato users choosing restaurants in Bangalore.
- Column-wise concatenation with axis=1 allows Zomato to integrate new data (e.g., delivery performance metrics) from external sources, such as logistics partners, into the existing restaurant dataset.
- This enriched dataset supports Zomato in optimizing delivery operations, prioritizing restaurants with faster delivery times for user recommendations, or identifying restaurants needing logistics improvements to enhance customer satisfaction.

### Practice Questions

1. **Using `.iloc`**, retrieve the first two rows and the last column.

In [ ]:
# 1. Using `.iloc` to retrieve the first two rows and the last column
sample_df.iloc[:2, -1]

0    4.1
1    4.7
Name: Rating, dtype: float64

2. **Using `.loc`**, update the 'Rating' for restaurants with votes below 150 to 4.0.

In [ ]:
# 2. Using `.loc` to update 'Rating' for restaurants with votes < 150
sample_df.loc[sample_df["Votes"] < 150, "Rating"] = 4.0
sample_df

  Restaurant  Votes  Rating
0         R1    120     4.0
1         R2    300     4.7
2         R3    180     4.2
3         R4     80     4.0

3. Add a new row to the DataFrame for a restaurant 'R7' with 100 votes and a rating of 3.7.

In [ ]:
# 3. Adding a new row,
new_row = pd.DataFrame([["R7", 100, 3.7]], columns=sample_df.columns)
sample_df = pd.concat([sample_df, new_row], ignore_index=True)
sample_df

  Restaurant  Votes  Rating
0         R1    120     4.0
1         R2    300     4.7
2         R3    180     4.2
3         R4     80     4.0
4         R7    100     3.7

4. Concatenate two DataFrames:
   - One with restaurant data.
   - One with a column showing average delivery time.

In [ ]:
# 4. Concatenating two DataFrames
df_with_time = pd.DataFrame({"Delivery Time (mins)": [30, 40, 20, 35, 25]})
final_combined_df = pd.concat([sample_df, df_with_time], axis=1)
final_combined_df

  Restaurant  Votes  Rating  Delivery Time (mins)
0         R1    120     4.0                    30
1         R2    300     4.7                    40
2         R3    180     4.2                    20
3         R4     80     4.0                    35
4         R7    100     3.7                    25

5. Find the updated 'Rating' for restaurants with votes greater than 200 after combining two DataFrames.

In [ ]:
# 5. Finding updated 'Rating' for restaurants with votes > 200
updated_ratings = final_combined_df.loc[final_combined_df["Votes"] > 200, "Rating"]
print(updated_ratings)

1    4.7
Name: Rating, dtype: float64

# Handling Duplicate Records in a DataFrame

I would showcase using the current dataset itself, instead of creating a new df. Creating story lines for removing duplicates is easy anyway.

In real-world datasets, duplicate records are common and can affect analysis. Pandas provides simple methods to identify and remove duplicates efficiently.

## <span style="color: skyblue;"> Key Methods for Handling Duplicates </span>

### 1. Identifying Duplicate Rows with `df.duplicated().`

The `df.duplicated()` method:
- Returns `True` for duplicate rows (excluding the first occurrence by default).
- You can customize its behavior using the `keep` parameter:
  - `keep='first'` (default): Marks all duplicates except the first occurrence.
  - `keep='last'`: Marks all duplicates except the last occurrence.
  - `keep=False`: Marks **all** duplicates as `True`.


> [Interactive]: Learn how duplicates are identified and handled step by step before exploring the code:
[Duplicates Handling Visualizer](https://aiml-v-izs.vercel.app/v/az-j9x3r6t1/pd-duplicates)

In [ ]:
# Example DataFrame
data = {
    "Restaurant": ["R1", "R2", "R3", "R2", "R4", "R1"],
    "Votes": [120, 240, 150, 240, 80, 120],
    "Rating": [4.1, 4.5, 3.9, 4.5, 4.0, 4.1]
}

sample_df = pd.DataFrame(data)
sample_df

  Restaurant  Votes  Rating
0         R1    120     4.1
1         R2    240     4.5
2         R3    150     3.9
3         R2    240     4.5
4         R4     80     4.0
5         R1    120     4.1

In [ ]:
# Identifying duplicate rows
print("Duplicate rows (keep='first'):")
print(sample_df.duplicated())  # Default behavior

Duplicate rows (keep='first'):
0    False
1    False
2    False
3     True
4    False
5     True
dtype: bool

In [ ]:
print("Duplicate rows (keep='last'):")
print(sample_df.duplicated(keep="last"))

Duplicate rows (keep='last'):
0     True
1     True
2    False
3    False
4    False
5    False
dtype: bool

In [ ]:
print("Duplicate rows (keep=False):")
print(sample_df.duplicated(keep=False))

Duplicate rows (keep=False):
0     True
1     True
2    False
3     True
4    False
5     True
dtype: bool

**Key Points**
- **Default (`keep='first'`)**: Treats the first occurrence of a duplicate as unique.
- **`keep='last'`**: Treats the last occurrence of a duplicate as unique.
- **`keep=False`**: Marks all duplicates as `True`.

### <span style=color:orange> Zomato Business Context:</span>

- Identifying duplicates ensures Zomato’s dataset accurately represents unique restaurants, preventing inflated metrics like total votes or skewed average ratings.
- For example, duplicate entries for a restaurant like “Cafe Coffee Day” could overstate its popularity, affecting recommendation algorithms or marketing decisions.
Checking duplicates helps Zomato maintain data integrity, ensuring reliable insights for user recommendations, restaurant rankings, or market coverage analysis in Bangalore.


### 2. Removing Duplicate Rows

The `df.drop_duplicates()` method removes duplicate rows based on the specified conditions:
- By default, it keeps the first occurrence of each duplicate row.
- You can use the `keep` parameter to change this behavior.

In [ ]:
# Removing duplicates (keep='first')
df_no_duplicates_first = sample_df.drop_duplicates(keep="first")
print("DataFrame after removing duplicates (keep='first'):")
print(df_no_duplicates_first)

DataFrame after removing duplicates (keep='first'):
  Restaurant  Votes  Rating
0         R1    120     4.1
1         R2    240     4.5
2         R3    150     3.9
4         R4     80     4.0

In [ ]:
# Removing duplicates (keep='last')
df_no_duplicates_last = sample_df.drop_duplicates(keep="last")
print("DataFrame after removing duplicates (keep='last'):")
print(df_no_duplicates_last)

DataFrame after removing duplicates (keep='last'):
  Restaurant  Votes  Rating
2         R3    150     3.9
3         R2    240     4.5
4         R4     80     4.0
5         R1    120     4.1

In [ ]:
# Removing all duplicates (keep=False)
df_no_duplicates_all = sample_df.drop_duplicates(keep=False)
print("DataFrame after removing all duplicates (keep=False):")
print(df_no_duplicates_all)

DataFrame after removing all duplicates (keep=False):
  Restaurant  Votes  Rating
2         R3    150     3.9
4         R4     80     4.0

### 3. Removing Duplicates Based on Specific Columns

Sometimes, you might want to check duplicates only for certain columns. Use the `subset` parameter in `df.drop_duplicates()` to specify the columns to consider for duplication.

- Use `subset` in `df.drop_duplicates()` to check duplicates for specific columns.

In [ ]:
# Removing duplicates based on the 'Votes' column
df_no_duplicates_subset = sample_df.drop_duplicates(subset=["Votes"], keep="first")
print("DataFrame after removing duplicates based on 'Votes':")
print(df_no_duplicates_subset)

DataFrame after removing duplicates based on 'Votes':
  Restaurant  Votes  Rating
0         R1    120     4.1
1         R2    240     4.5
2         R3    150     3.9
4         R4     80     4.0

In [ ]:
# Removing duplicates based on 'Restaurant' and 'Votes.'
df_no_duplicates_multi_subset = sample_df.drop_duplicates(subset=["Restaurant", "Votes"], keep="first")
print("DataFrame after removing duplicates based on 'Restaurant' and 'Votes':")
print(df_no_duplicates_multi_subset)

DataFrame after removing duplicates based on 'Restaurant' and 'Votes':
  Restaurant  Votes  Rating
0         R1    120     4.1
1         R2    240     4.5
2         R3    150     3.9
4         R4     80     4.0

### <span style=color:orange> Zomato Business Context:</span>

- Removing duplicates based on Total_Votes ensures Zomato avoids overcounting restaurants with identical review counts, refining popularity metrics for user recommendations.
- Using subset=["name", "Total_Votes"] checks for restaurants with the same name and vote count, which could indicate erroneous duplicate entries (e.g., a chain listed twice in the same location), improving data quality for restaurant rankings.
- These operations help Zomato maintain a clean dataset, ensuring accurate insights for marketing campaigns, delivery logistics, or identifying top-performing restaurants in Bangalore.

# Question
Which statement about `df.drop_duplicates()` is FALSE?
# Choices
- [ ] By default, it keeps the first occurrence of each duplicate row
- [ ] The subset parameter lets you specify columns to check duplicates
- [x] It modifies the DataFrame in-place without needing `inplace=True`
- [ ] The `keep=False` option removes all duplicates


Explanation:
By default, `df.drop_duplicates()` returns a new DataFrame and does not modify the original one.


To apply changes directly, you must explicitly pass `inplace=True`.

# Pandas Built-In Operations - Aggregate Functions

[Interactive]: Understand how aggregate functions compute summaries across data step by step before diving into the code:
[Aggregate Functions Visualizer](https://aiml-v-izs.vercel.app/v/az-j9x3r6t1/pd-aggregation)

> Show different operations from dropdown.

In [ ]:
# Sum of votes
print("Total Votes:", df["Total_Votes"].sum())

Total Votes: 13940720

In [ ]:
# Count of ratings
print("Number of Ratings:", df["only_rating"].count())

Number of Ratings: 23046

In [ ]:
# Average cost for two
print("Average Cost for Two:", df["cost_for_two"].mean())

Average Cost for Two: 755.90436769715

## <span style="color: skyblue;"> Applying Aggregate Functions on Multiple Columns </span>
You can also apply aggregate functions across multiple columns using the .agg() method.

**Example: Aggregating Across Columns**

In [ ]:
# Aggregating multiple columns
aggregates = df[["Total_Votes", "cost_for_two"]].agg(["sum", "mean", "min", "max"])
print("Aggregates for Votes and Cost for Two:")
aggregates

Aggregates for Votes and Cost for Two:

       Total_Votes  cost_for_two
sum   1.394072e+07  1.753169e+07
mean  6.010745e+02  7.559044e+02
min   0.000000e+00  4.000000e+01
max   1.683200e+04  6.000000e+03

### <span style=color:orange> Zomato Business Context:</span>

- Using .agg() on Total_Votes and cost_for_two reveals key metrics, such as total engagement (sum), average costs (mean), and cost range (min, max), helping Zomato identify market trends.
- For example, a high max cost could highlight premium restaurants for Zomato Gold promotions, while a low min cost could inform budget-friendly dining campaigns.
- These aggregates support strategic decisions, like optimizing restaurant recommendations, targeting marketing in high-engagement areas, or advising restaurant partners on pricing strategies in Bangalore.

# Sorting Values in Pandas

> [Interactive]: See how sorting rearranges data step by step before diving into the code:
[Sorting Visualizer](https://aiml-v-izs.vercel.app/v/az-j9x3r6t1/pd-sorting)

## <span style="color: skyblue;"> Sorting by a Single Column </span>

In [ ]:
# Sorting rows by the "Votes" column in ascending order
sorted_votes_asc = sample_df.sort_values(by="Votes", ascending=True)
print("DataFrame sorted by Votes (ascending):")
print(sorted_votes_asc)

DataFrame sorted by Votes (ascending):
  Restaurant  Votes  Rating
4         R4     80     4.0
0         R1    120     4.1
5         R1    120     4.1
2         R3    150     3.9
3         R2    240     4.5
1         R2    240     4.5

In [ ]:
# Sorting rows by the "Votes" column in descending order
sorted_votes_desc = sample_df.sort_values(by="Votes", ascending=False)
print("DataFrame sorted by Votes (descending):")
print(sorted_votes_desc)

DataFrame sorted by Votes (descending):
  Restaurant  Votes  Rating
1         R2    240     4.5
3         R2    240     4.5
2         R3    150     3.9
0         R1    120     4.1
5         R1    120     4.1
4         R4     80     4.0

## <span style="color: skyblue;"> Sorting by Multiple Columns </span>

**Example: Sorting by "Votes" and "Rating"**

You can sort rows based on multiple columns by passing a list of column names.

In [ ]:
# Sorting by Votes (descending) and then by Rating (ascending)
sorted_multi = sample_df.sort_values(by=["Votes", "Rating"], ascending=[False, True])
print("DataFrame sorted by Votes (descending) and Rating (ascending):")
sorted_multi

DataFrame sorted by Votes (descending) and Rating (ascending):

  Restaurant  Votes  Rating
1         R2    240     4.5
3         R2    240     4.5
2         R3    150     3.9
0         R1    120     4.1
5         R1    120     4.1
4         R4     80     4.0

### <span style=color:orange> Zomato Business Context:</span>

- Sorting by Total_Votes (descending) and only_rating (ascending) ranks highly engaged restaurants while resolving ties by rating, helping Zomato identify top-performing restaurants for recommendations or Zomato Gold promotions.
- This approach supports nuanced analysis, such as finding restaurants with high votes but lower ratings, which may need support from Zomato’s restaurant success team to improve customer satisfaction in Bangalore.


**Some Practice Questions**

<span style="background-color: red;"> **[Ask Learners]:** </span>
Give them some time (around 2 min) to solve the following one by one and then show the answer.

1. Sort the DataFrame by "Rating" in descending order.
2. Find the restaurant with the highest rating after sorting.
3. Sort the DataFrame first by "Cost for Two" (ascending) and then by "Votes" (descending).
4. Create a new sorted DataFrame based on "Votes" and "Rating" and display the top 3 rows.

In [ ]:
import numpy as np
def rearrange_image(data, num_splits):
    # 1. Split the image using np.vsplit
    sections = np.vsplit(data, num_splits)

    # 2. Rearrange sections
    modified_sections = sections[-1:] + sections[:-1]  # Cyclic shift

    # 3. Return the modified array
    return np.concatenate(modified_sections)

# Question
Consider `df.sort_values(by="age", ascending=[True, False])`. Why might this throw an error?
# Choices
- [ ] Because ascending must be a single boolean, not a list
- [x] Because ascending list length must match number of columns in by
- [ ] Because age must be numeric to sort
- [ ] Because sorting cannot be done in-place

Explanation:

- `df.sort_values()` allows multi-column sorting.


- When by is a list of multiple columns, you can pass a list of booleans to ascending (one per column).


- But if `by="age"` (just a single column), then:


    - ascending should either be a single boolean (True/False),


    - OR a list of length 1 (e.g., `[True]`).


- Passing `[True, False]` causes a length mismatch error.

# About the Dataset and Business Case of **Amazon**

**Dataset:** <font color="violet">**Retail Product Reviews**</font> 🛍  
We are exploring a retail dataset that includes **product information** and **customer reviews**. By analyzing this data, we aim to understand:

- Trends in <font color="blue">**product ratings**</font> and <font color="green">**discount effectiveness**</font>.
- Insights from <font color="purple">**customer reviews**</font> to assess product reception.
- Relationships between <font color="orange">**pricing, discounts, and ratings**</font>.
- The significance of <font color="red">**categories**</font> in influencing purchasing behavior.

### **Key Business Objectives:**
1. <font color="teal">**Enhance Customer Experience**</font>: Understand customer sentiment through reviews and ratings.
2. <font color="teal">**Boost Revenue with Discounts**</font>: Analyze the effect of discount percentages on sales and reviews.
3. <font color="teal">**Product Optimization**</font>: Identify top-performing product categories for focused marketing strategies.
4. <font color="teal">**Inform Pricing Strategies**</font>: Use insights from rating trends and pricing.

We’ll use this dataset as a running example to demonstrate techniques in data analysis and, later, how <font color="magenta">**NumPy**</font> and <font color="magenta">**pandas**</font> can simplify merging and analyzing structured data efficiently.

<font color="blue">**Note:**</font> Here is our initial look at the data. We see columns like:
- <font color="orange">`product_id`</font> (unique identifier for products, key for merging datasets)
- <font color="purple">`review_content`</font> & <font color="green">`rating`</font> (customer feedback and sentiment analysis)
- <font color="red">`discount_percentage`</font> & <font color="brown">`actual_price`</font> (pricing insights)

This dataset offers a rich foundation to explore merging operations and practical use cases in retail analytics.

Now, we will be loading the dataset that includes product information and customer reviews.

# Loading the dataset

### **Dataset Link:** <span style="background-color: Blue;">[Amazon Sales Data](https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/101/214/original/amazon_data4.zip)</span>

In [ ]:
!wget https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/101/214/original/amazon_data4.zip

--2026-01-19 10:16:23--  https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/101/214/original/amazon_data4.zip
Resolving d2beiqkhq929f0.cloudfront.net (d2beiqkhq929f0.cloudfront.net)... 18.239.15.127, 18.239.15.11, 18.239.15.217, ...
Connecting to d2beiqkhq929f0.cloudfront.net (d2beiqkhq929f0.cloudfront.net)|18.239.15.127|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1943535 (1.9M) [application/zip]
Saving to: ‘amazon_data4.zip’

amazon_data4.zip    100%[===================>]   1.85M  --.-KB/s    in 0.03s

2026-01-19 10:16:23 (62.4 MB/s) - ‘amazon_data4.zip’ saved [1943535/1943535]

In [ ]:
!unzip amazon_data4.zip

Archive:  amazon_data4.zip
  inflating: products.csv
  inflating: orders.csv

#### Reading the dataset:

In [ ]:
import pandas as pd

orders = pd.read_csv('orders.csv')
orders.head()

,product_id,user_id,user_name,review_id,review_title,review_content,order_timestamp
0,B07JW9H4J1,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,2023-01-01 00:00:00.000000000
1,B098NS6PVG,"AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,2023-01-01 05:58:01.967213114
2,B096MSW6CT,"AGU3BBQ2V2DDAMOAKGFAWDDQ6QHA,AESFLDV2PT363T2AQ...","Kunal,Himanshu,viswanath,sai niharka,saqib mal...","R3J3EQQ9TZI5ZJ,R3E7WBGK7ID0KV,RWU79XKQ6I1QF,R2...","Good speed for earlier versions,Good Product,W...","Not quite durable and sturdy,https://m.media-a...",2023-01-01 11:56:03.934426229
3,B08HDJ86NZ,"AEWAZDZZJLQUYVOVGBEUKSLXHQ5A,AG5HTSFRRE6NL3M5S...","Omkar dhale,JD,HEMALATHA,Ajwadh a.,amar singh ...","R3EEUZKKK9J36I,R3HJVYCLYOY554,REDECAZ7AMPQC,R1...","Good product,Good one,Nice,Really nice product...","Good product,long wire,Charges good,Nice,I bou...",2023-01-01 17:54:05.901639344
4,B08CF3B7N1,"AE3Q6KSUK5P75D5HFYHCRAOLODSA,AFUGIFH5ZAFXRDSZH...","rahuls6099,Swasat Borah,Ajay Wadke,Pranali,RVK...","R1BP4L2HH9TFUP,R16PVJEXKV6QZS,R2UPDB81N66T4P,R...","As good as original,Decent,Good one for second...","Bought this instead of original apple, does th...",2023-01-01 23:52:07.868852459

In [ ]:
products = pd.read_csv('products.csv')
products.head()

,product_id,product_name,category,discounted_price,actual_price,rating,rating_count,about_product,img_link,product_link
0,B07JW9H4J1,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories,₹399,"₹1,099",4.2,24269.0,High Compatibility : Compatible With iPhone 12...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
1,B098NS6PVG,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories,₹199,₹349,4.0,43994.0,"Compatible with all Type C enabled devices, be...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...
2,B096MSW6CT,Sounce Fast Phone Charging Cable & Data Sync U...,Computers&Accessories,₹199,"₹1,899",3.9,7928.0,【 Fast Charger& Data Sync】-With built-in safet...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Sounce-iPhone-Charging-C...
3,B08HDJ86NZ,boAt Deuce USB 300 2 in 1 Type-C & Micro USB S...,Computers&Accessories,₹329,₹699,4.2,94363.0,The boAt Deuce USB 300 2 in 1 cable is compati...,https://m.media-amazon.com/images/I/41V5FtEWPk...,https://www.amazon.in/Deuce-300-Resistant-Tang...
4,B08CF3B7N1,Portronics Konnect L 1.2M Fast Charging 3A 8 P...,Computers&Accessories,₹154,₹399,4.2,16905.0,[CHARGE & SYNC FUNCTION]- This cable comes wit...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Portronics-Konnect-POR-1...

Now, we will be learning how to merge these two datasets.

## <span style="color: skyblue;"> Merging DataFrames </span>

Just like we can merge two Excel sheets, we can also merge two dataframes.


#### Concatenation:
`pd.concat()` is used to stack DataFrames either **vertically (rows) or horizontally (columns)**. However, it doesn’t align DataFrames based on keys.

![1](https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/153/922/original/1.png?1758519701)

- `axis = 0` - merging along rows
- `axis = 1` - merging along columns

#### Merge:
`pd.merge()` allows you to combine DataFrames based on **one or more keys (common columns)**. This aligns rows based on these keys, making it more flexible and accurate for relational joins.

![2](https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/153/924/original/2.png?1758520194)

This `merge` operation is done along a unique column to have a relation between the two dataframes.


## <span style="color: skyblue;"> Joins in SQL </span>


We are assuming that most of you might have learnt joins in SQL.

![3](https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/153/926/original/3.webp?1758520912)


**Joins in pandas** replicate SQL-style joins:
- **Inner Join**: Returns rows with matching keys in both DataFrames.
- **Outer Join**: Returns all rows, with missing values filled as `NaN`.
- **Left Join**: Keeps all rows from the left DataFrame and matches from the right.
- **Right Join**: Keeps all rows from the right DataFrame and matches from the left.


> [Interactive]: Visualize how merge and join operations combine datasets step by step before diving into the code:
[Merge & Join Visualizer](https://aiml-v-izs.vercel.app/v/az-j9x3r6t1/pd-merging)


Let's understand these joins using a sample dataset:

**Inner Join**: Combines only matching rows based on product_id.

In [ ]:
# Import pandas
import pandas as pd

# Sample DataFrames
samples_orders = pd.DataFrame({
    'product_id': ['P001', 'P002', 'P003'],
    'user_id': ['U001', 'U002', 'U003'],
    'review_id': ['R001', 'R002', 'R003']
})

samples_products = pd.DataFrame({
    'product_id': ['P001', 'P002', 'P004'],
    'product_name': ['Product A', 'Product B', 'Product D'],
    'category': ['Category 1', 'Category 2', 'Category 3']
})

# Inner Join Example
inner_join = pd.merge(samples_orders, samples_products, on='product_id', how='inner')
print("Inner Join:")
print(inner_join)

Inner Join:
  product_id user_id review_id product_name    category
0       P001    U001      R001    Product A  Category 1
1       P002    U002      R002    Product B  Category 2

- We can see that the common column is `product_id`.
- Hence, the joins are based on the `product_id`.
- In an inner join, only the common IDs are joined, and the rest are ignored.


<span style="background-color: red;"> **[Ask Learners]:** </span>
Try the other types of joins (`outer`, `left` and `right`) now and observe the differences. Let learner try them out.

**Outer Join**
Combines all rows from both DataFrames, filling unmatched columns with `NaN`.

In [ ]:
# Outer Join Example
outer_join = pd.merge(samples_orders,
                      samples_products, on='product_id', how='outer')
print("\nOuter Join:")
print(outer_join)

Outer Join:
  product_id user_id review_id product_name    category
0       P001    U001      R001    Product A  Category 1
1       P002    U002      R002    Product B  Category 2
2       P003    U003      R003          NaN         NaN
3       P004     NaN       NaN    Product D  Category 3

To learn about the syntax, you can use the help page by just writing `pd.merge`.


### <span style="color: violet;"> **Which Join is Best in Our Case?** </span>

#### **Best Join: Left Join**
For our scenario, the **Left Join** is the best choice because:
1. It keeps all rows from the `orders` DataFrame.
2. It adds product information only for matching `product_ids, leaving unmatched products as `NaN`.

This ensures we don’t lose any `orders` data while still enriching the dataset with available product details.

In [ ]:
# Performing a Left Join to merge orders with product details
df = pd.merge(orders, products, on='product_id', how='left')

# Displaying the result
print("Best Join (Left Join) for Our Use Case:")
df.head()

Best Join (Left Join) for Our Use Case:

,product_id,user_id,user_name,review_id,review_title,review_content,order_timestamp,product_name,category,discounted_price,actual_price,rating,rating_count,about_product,img_link,product_link
0,B07JW9H4J1,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,2023-01-01 00:00:00.000000000,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories,₹399,"₹1,099",4.2,24269.0,High Compatibility : Compatible With iPhone 12...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
1,B07JW9H4J1,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,2023-01-01 00:00:00.000000000,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories,₹399,"₹1,099",4.2,24270.0,High Compatibility : Compatible With iPhone 12...,https://m.media-amazon.com/images/I/51UsScvHQN...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
2,B07JW9H4J1,"AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...","Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...","R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...","Satisfied,Charging is really fast,Value for mo...",Looks durable Charging is fine tooNo complains...,2023-01-01 00:00:00.000000000,Wayona Nylon Braided USB to Lightning Fast Cha...,Computers&Accessories,₹399,"₹1,099",4.2,24269.0,High Compatibility : Compatible With iPhone 12...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
3,B098NS6PVG,"AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,2023-01-01 05:58:01.967213114,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories,₹199,₹349,4.0,43994.0,"Compatible with all Type C enabled devices, be...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...
4,B098NS6PVG,"AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,2023-01-01 05:58:01.967213114,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories,₹199,₹349,4.0,43993.0,"Compatible with all Type C enabled devices, be...",https://m.media-amazon.com/images/I/31zOsqQOAO...,https://www.amazon.in/Ambrane-Unbreakable-Char...

# Question
When merging DataFrames in Pandas, which statement is conceptually correct?
# Choices
- [x] If you don’t specify `on=`, Pandas will automatically merge on all columns with the same name.
- [ ] By default, Pandas performs a left join.
- [ ] Merging always results in duplicate rows if the join keys are not unique.
- [ ] If both DataFrames have an index with the same name, Pandas will automatically merge on it.

## <span style="color: skyblue;"> Applying Functions with `.apply()` </span>

`.apply()` is a powerful method in pandas to apply custom or predefined functions to DataFrame columns or rows.

In [ ]:
df['review_title'].head()

0    Satisfied,Charging is really fast,Value for mo...
1    Satisfied,Charging is really fast,Value for mo...
2    Satisfied,Charging is really fast,Value for mo...
3    A Good Braided Cable for Your Type C Device,Go...
4    A Good Braided Cable for Your Type C Device,Go...
Name: review_title, dtype: object

Now, we have a dataset with the column `review_title`. We want to convert this data into `Uppercase`.

In [ ]:
def uppercase_title(title):
    return title.upper()

df['review_title_uppercase'] = df['review_title'].apply(uppercase_title)

df['review_title_uppercase'].head()

0    SATISFIED,CHARGING IS REALLY FAST,VALUE FOR MO...
1    SATISFIED,CHARGING IS REALLY FAST,VALUE FOR MO...
2    SATISFIED,CHARGING IS REALLY FAST,VALUE FOR MO...
3    A GOOD BRAIDED CABLE FOR YOUR TYPE C DEVICE,GO...
4    A GOOD BRAIDED CABLE FOR YOUR TYPE C DEVICE,GO...
Name: review_title_uppercase, dtype: object

This operation can also be performed using a lambda function.

In [ ]:
orders['review_title_uppercase'] = orders['review_title'].apply(lambda x: x.upper())

df['review_title_uppercase'].head()

0    SATISFIED,CHARGING IS REALLY FAST,VALUE FOR MO...
1    SATISFIED,CHARGING IS REALLY FAST,VALUE FOR MO...
2    SATISFIED,CHARGING IS REALLY FAST,VALUE FOR MO...
3    A GOOD BRAIDED CABLE FOR YOUR TYPE C DEVICE,GO...
4    A GOOD BRAIDED CABLE FOR YOUR TYPE C DEVICE,GO...
Name: review_title_uppercase, dtype: object

- In the above code, `x` is the input for the function.

Let's do some interesting operations on the datasets:

In [ ]:
print(df['discounted_price'].head())
print(df['actual_price'].head())

0    ₹399
1    ₹399
2    ₹399
3    ₹199
4    ₹199
Name: discounted_price, dtype: object
0    ₹1,099
1    ₹1,099
2    ₹1,099
3      ₹349
4      ₹349
Name: actual_price, dtype: object

Let's remove the `rupee` symbol and `,` from the above datasets and convert them in integer.

In [ ]:
def extract_price(price_str):
    try:
        return float(str(price_str).replace('₹', '').replace(',', ''))
    except ValueError:
        return None

# Apply the function to the 'actual_price' and 'discounted_price' columns
df['actual_price'] = df['actual_price'].apply(extract_price)
df['discounted_price'] = df['discounted_price'].apply(extract_price)

print(df['discounted_price'].head())
print(df['actual_price'].head())

0    399.0
1    399.0
2    399.0
3    199.0
4    199.0
Name: discounted_price, dtype: float64
0    1099.0
1    1099.0
2    1099.0
3     349.0
4     349.0
Name: actual_price, dtype: float64

<span style="background-color: red;"> **[Ask Learners]:** </span>
<span style="color: violet;"> How can we find the discount percentage from these two columns? </span>

Now, let's calculate the discount percentage for the product items.

In [ ]:
# Define a function to calculate the effective discount percentage
def calculate_discount_percentage(row):
    return ((row['actual_price'] - row['discounted_price']) / row['actual_price']) * 100

# Apply the function along rows (axis=1)
df['calculated_discount'] = df.apply(calculate_discount_percentage, axis=1)

# Display the result
print("Products DataFrame with Calculated Discounts:")
df[['product_name', 'actual_price', 'discounted_price', 'calculated_discount']].head()

Products DataFrame with Calculated Discounts:

,product_name,actual_price,discounted_price,calculated_discount
0,Wayona Nylon Braided USB to Lightning Fast Cha...,1099.0,399.0,63.694268
1,Wayona Nylon Braided USB to Lightning Fast Cha...,1099.0,399.0,63.694268
2,Wayona Nylon Braided USB to Lightning Fast Cha...,1099.0,399.0,63.694268
3,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,349.0,199.0,42.979943
4,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,349.0,199.0,42.979943

- One important point to remember is that `axis = 1` must be assigned to ensure that the operations are performed along the rows.


Let's see how can we execute multiple operations for multiple columns.

In [ ]:
# Define aggregate functions to calculate max and min
def max_rating(series):
    return series.max()

def min_rating_count(series):
    return series.min()

# Apply the functions across columns
rating_stats = products[['rating', 'rating_count']].apply([max_rating, min_rating_count])

# Display the result
print("Rating Statistics:")
print(rating_stats)

Rating Statistics:
                  rating  rating_count
max_rating           5.0      426973.0
min_rating_count     2.0           2.0

Let's see how can we find the info about the `null` values.

In [ ]:
df.isnull().sum()

product_id                 0
user_id                    0
user_name                  0
review_id                  0
review_title               0
review_content             0
order_timestamp            0
product_name               0
category                  13
discounted_price          13
actual_price               8
rating                    20
rating_count               2
about_product              0
img_link                   0
product_link               0
review_title_uppercase     0
calculated_discount       21
dtype: int64

- This function will be used very frequently in the upcoming time when we will be discussing the projects.

In [ ]:
df.to_csv('data.csv', index=False)

# Question
Why might `.apply()` be considered less efficient than vectorized operations in Pandas?
# Choices
- [ ] Because `.apply()` always converts data to Python lists before applying the function.
- [x] Because `.apply()` often runs a Python-level loop, breaking Pandas’ vectorization advantage.
- [ ] Because `.apply()` modifies the underlying DataFrame copy, requiring extra memory.
- [ ] Because `.apply()` only supports functions defined with lambda, not built-ins.

Explanation:

`apply()` is often less efficient than vectorized operations because:

- Pandas’ strength comes from vectorized operations (built on NumPy C-extensions), which are highly optimized.


- When you use `.apply()`, Pandas usually executes a Python-level loop internally.


- That means instead of leveraging fast, low-level array operations, it falls back to slower Python execution.

# Question
Which of the following is the most accurate description of `.apply()` with `axis=1`?
# Choices
- [ ] It vectorizes row-wise operations across all columns.
- [x] It applies the function once per row, passing the entire row as a Series.
- [ ] It applies the function on each column separately.
- [ ] It modifies the DataFrame inplace without returning anything.


Explanation: `axis=1` → function applied row by row, with each row passed as a Series. This is not vectorized; it’s slower. Many confuse it with NumPy-style row-wise vectorization.

# <span style="color: skyblue;"> Grouping in Pandas </span>

Grouping is a powerful feature in pandas that allows us to perform operations on subsets of the data. The process can be broken down into three main steps:

1. **Split:** Divide the data into groups based on a key or multiple keys.
2. **Apply:** Perform a specific operation (e.g., aggregation, transformation, or filtering) on each group.
3. **Combine:** Bring the results together into a new DataFrame or Series.

Let's see this example to understand it visually.

![4](https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/153/929/original/4.png?1758524042)

> [Interactive]: Visualize how groupby splits data into groups based on keys before applying any operations:
[GroupBy Split Visualizer](https://aiml-v-izs.vercel.app/v/az-j9x3r6t1/pd-groupby-split)

> Note: This only visualize the splits like the above image.

### <span style=color:orange> Business Context:</span>

Amazon handles vast amounts of data across its e-commerce platform, including customer orders, product sales, and inventory records. Grouping data by keys like product categories, regions, or customer segments allows Amazon to analyze trends, optimize inventory, and tailor marketing strategies. Using pandas’ grouping functionality, Amazon can split data (e.g., by product category), apply operations like summing sales or averaging ratings, and combine results to generate actionable insights. This supports critical business decisions, such as identifying top-performing product categories, optimizing stock levels, or personalizing customer recommendations.


## **1. Group-Based Aggregations**

We can use <font color="magenta">`.groupby()`</font> to perform aggregation functions such as `sum`, `min`, `max`, `count`, etc., for each group. Let’s start with some examples.

> [Interactive]: See how groupby applies aggregate functions to each group and combines the results step by step:
[GroupBy Aggregation Visualizer](https://aiml-v-izs.vercel.app/v/az-j9x3r6t1/pd-groupby)

> Show different operation from dropdwon

**Example 1: Group by a Single Column**
- **Goal:** Find the average `calculated_discount` for each `category`.

In [ ]:
## How can Amazon analyze average discount percentages by product category to identify which categories
## have the most effective discount strategies for driving sales?

# Example 1: Group by 'category' and calculate the average 'discounted_price'
avg_discounted_price = df.groupby('category')['calculated_discount'].mean()

# Display the results
print("Average Discounted Percentage by Category:")
avg_discounted_price

Average Discounted Percentage by Category:

category
Car&Motorbike            41.525000
Computers&Accessories    55.374270
Electronics              52.152439
Health&PersonalCare      52.684211
Home&Kitchen             40.241448
HomeImprovement          57.944088
MusicalInstruments       45.808298
OfficeProducts           12.771811
Toys&Games                0.000000
Name: calculated_discount, dtype: float64

**Example 2: Count of products per user**

- **Goal:** Compute the count `product` for each `user`.

In [ ]:
# Example:
count_product_user = df.groupby('user_name')['product_name'].count()
count_product_user[:10]

user_name
$@|\|TO$|-|,Sethu madhav,Akash Thakur,Burger Planet,Justice ⚖️,indrajyoti d.,Aditya Kumar,E.C.GEORGE                             16
& I Am IronMan,Amazon Customer,Sayandeep Sarkar,sherin                                                                            1
(sic),Harshit,Bharath N,Pulkit Malik,Akhtar Anwar,Amar  Thapa,Chandan kumar,vijay                                                 1
123MovieTime,Ravneet S.,Akash,Mohd Amaan,Pankaj,Sajan                                                                             1
9640185788,Piyush Mishra,Vickie,Sakshi gupta,Srinivas,Lovraj V.,Rakshitha,Sandeep Kumar Yadav                                     1
9848023076,Parimala,ajay kumar verma,ARSHAD,Hola,Anil V,kuppannan maruthachalam,Nikhil                                            1
A H.,Amazon Customer,Amazon Customer,Gajendra Kumar sharma,Harpreet Kaur Sodhi,Shashi ranjan Kumar,Chandan Kumar,Vikas sharma     1
A K Rai,Poojitha Subrahmanyam Naralasetti,Mugiwara,Arasu,Suraj M.,Vasudeva,Praveen Ramachandruni,Bhaskar Choudhuri                1
A. Dubey,anandmohan,PREM,Daanish Daaivik,A,Amazon Customer,Jitendra padhi,Kritkalp                                                1
A.D.PAUL & CO.,Suraj,PRATEEK KUMAR RAI,Swarn Gupta,kalyan,Esther,Krishna chaithanya,NILIM                                         1
Name: product_name, dtype: int64

**Example 3: Maximum and Minimum Rating Count by Category and Product Name**
- **Goal:** Find the maximum and minimum `rating_count` for each combination of `category` and `product_name`.

In [ ]:
# Example: Maximum and minimum rating count by category and product name
rating_stats = df.groupby(['category', 'product_name'])['rating_count'].agg(['max', 'min'])

print("\nMaximum and Minimum Rating Count by Category and Product Name:")
rating_stats[:10]

Maximum and Minimum Rating Count by Category and Product Name:

                                                                              max  \
category              product_name
Car&Motorbike         Reffair AX30 [MAX] Portable Air Purifier for Ca...   1118.0
Computers&Accessories APC Back-UPS BX600C-IN 600VA / 360W, 230V, UPS ...  15783.0
                      Acer EK220Q 21.5 Inch (54.61 cm) Full HD (1920x...   2014.0
                      Agaro Blaze USBA to micro +Type C 2in1 Braided ...  14184.0
                      AirCase Protective Laptop Bag Sleeve fits Upto ...   9940.0
                      AirCase Protective Laptop Bag Sleeve fits Upto ...   9701.0
                      AirCase Protective Laptop Bag Sleeve fits Upto ...  11330.0
                      AirCase Rugged Hard Drive Case for 2.5-inch Wes...  21010.0
                      Airtel AMF-311WW Data Card (Black), 4g Hotspot ...  11213.0
                      Amazon Basics Magic Slate 8.5-inch LCD Writing ...    401.0

                                                                              min
category              product_name
Car&Motorbike         Reffair AX30 [MAX] Portable Air Purifier for Ca...   1118.0
Computers&Accessories APC Back-UPS BX600C-IN 600VA / 360W, 230V, UPS ...  15783.0
                      Acer EK220Q 21.5 Inch (54.61 cm) Full HD (1920x...   2014.0
                      Agaro Blaze USBA to micro +Type C 2in1 Braided ...  14184.0
                      AirCase Protective Laptop Bag Sleeve fits Upto ...   9940.0
                      AirCase Protective Laptop Bag Sleeve fits Upto ...   9701.0
                      AirCase Protective Laptop Bag Sleeve fits Upto ...  11330.0
                      AirCase Rugged Hard Drive Case for 2.5-inch Wes...  21010.0
                      Airtel AMF-311WW Data Card (Black), 4g Hotspot ...  11213.0
                      Amazon Basics Magic Slate 8.5-inch LCD Writing ...    401.0

## **2. Group-Based Filtering**

Group-based filtering in pandas allows us to retain groups that satisfy certain conditions. This is done using <font color="magenta">`.filter()`</font> on grouped DataFrames.

> [Interactive]: See how groupby filters groups based on conditions step by step before diving into the code:
[GroupBy Filter Visualizer](https://aiml-v-izs.vercel.app/v/az-j9x3r6t1/pd-groupby)

> Select the operation  filter from dropdown.

Here are some examples of group-based filtering using different columns from the **merged DataFrame**:

**Example 1: Filter Categories with Average Rating equal or above 4**
- **Goal:** Keep only categories where the average `rating` is greater than or equal to 4.


### <span style=color:orange> Business Context:</span>


Amazon’s e-commerce platform relies on product ratings to build customer trust and drive sales. Filtering product categories based on metrics like average ratings helps Amazon identify high-quality categories that meet customer expectations. Using pandas’ .filter() on grouped DataFrames allows Amazon to isolate categories with strong performance (e.g., average rating ≥ 4), enabling targeted marketing, quality assurance, or inventory prioritization. This ensures Amazon promotes top-rated categories, enhancing customer satisfaction and optimizing product offerings.

In [ ]:
# Example: Filter categories with an average rating >= 4
categories_high_rating = df.groupby('category')['rating'].mean().loc[lambda x: x >= 4]

# Display the results
print("Categories with High Average Rating (Above 4):")
categories_high_rating

Categories with High Average Rating (Above 4):

category
Computers&Accessories    4.158934
Electronics              4.090508
Health&PersonalCare      4.000000
Home&Kitchen             4.045890
HomeImprovement          4.250000
OfficeProducts           4.309677
Toys&Games               4.300000
Name: rating, dtype: float64

**Example 2: Filter Users Who Have Written More Than 15 Reviews**
- **Goal:** Retain only users (`user_id`) who have written more than 15 reviews.

In [ ]:
# Example: Filter users who have written more than 15 reviews
users_with_many_reviews = df.groupby('user_id').filter(
    lambda group: group['review_id'].count() > 15
)

users_with_many_reviews

,product_id,user_id,user_name,review_id,review_title,review_content,order_timestamp,product_name,category,discounted_price,actual_price,rating,rating_count,about_product,img_link,product_link,review_title_uppercase,calculated_discount
3,B098NS6PVG,"AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,2023-01-01 05:58:01.967213114,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories,199.00,349.0,4.0,43994.0,"Compatible with all Type C enabled devices, be...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...,"A GOOD BRAIDED CABLE FOR YOUR TYPE C DEVICE,GO...",42.979943
4,B098NS6PVG,"AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,2023-01-01 05:58:01.967213114,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories,199.00,349.0,4.0,43993.0,"Compatible with all Type C enabled devices, be...",https://m.media-amazon.com/images/I/31zOsqQOAO...,https://www.amazon.in/Ambrane-Unbreakable-Char...,"A GOOD BRAIDED CABLE FOR YOUR TYPE C DEVICE,GO...",42.979943
5,B098NS6PVG,"AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,2023-01-01 05:58:01.967213114,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories,199.00,349.0,4.0,43994.0,"Compatible with all Type C enabled devices, be...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...,"A GOOD BRAIDED CABLE FOR YOUR TYPE C DEVICE,GO...",42.979943
25,B082LZGK39,"AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,2023-01-03 05:42:17.704918032,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories,199.00,299.0,4.0,43994.0,Universal Compatibility – It is compatible wit...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...,"A GOOD BRAIDED CABLE FOR YOUR TYPE C DEVICE,GO...",33.444816
26,B082LZGK39,"AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,2023-01-03 05:42:17.704918032,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories,199.00,299.0,4.0,43994.0,Universal Compatibility – It is compatible wit...,https://m.media-amazon.com/images/I/31kj3q4Sep...,https://www.amazon.in/Ambrane-Unbreakable-Char...,"A GOOD BRAIDED CABLE FOR YOUR TYPE C DEVICE,GO...",33.444816
44,B082LSVT4B,"AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,2023-01-05 05:26:33.442622950,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories,249.00,399.0,4.0,43994.0,"Compatible with all Type C enabled devices, be...",https://m.media-amazon.com/images/I/41d84o5-M-...,https://www.amazon.in/Ambrane-Unbreakable-Char...,"A GOOD BRAIDED CABLE FOR YOUR TYPE C DEVICE,GO...",37.593985
45,B082LSVT4B,"AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,2023-01-05 05:26:33.442622950,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories,249.00,399.0,4.0,43994.0,"Compatible with all Type C enabled devices, be...",https://m.media-amazon.com/images/I/41d84o5-M-...,https://www.amazon.in/Ambrane-Unbreakable-Char...,"A GOOD BRAIDED CABLE FOR YOUR TYPE C DEVICE,GO...",37.593985
57,B09NHVCHS9,"AHIKJUDTVJ4T6DV6IUGFYZ5LXMPA,AE55KTFVNXYFD5FPY...","$@|\|TO$|-|,Sethu madhav,Akash Thakur,Burger P...","R3F4T5TRYPTMIG,R3DQIEC603E7AY,R1O4Z15FD40PV5,R...","Worked on iPhone 7 and didn’t work on XR,Good ...",Worked on iPhone 7 and didn’t work on iPhone X...,2023-01-06 17:14:45.245901639,Flix Micro Usb Cable For Smartphone (Black),Computers&Accessories,59.00,199.0,4.0,9378.0,"Micro usb cable is 1 meter in length, optimize...",https://m.media-amazon.com/images/I/31qGpf8uzu...,https://www.amazon.in/Flix-Micro-Cable-Smartph...,"WORKED ON IPHONE 7 AND DIDN’T WORK ON XR,GOOD ...",70.351759
58,B09NHVCHS9,"AHIKJUDTVJ4T6DV6IUGFYZ5LXMPA,AE55KTFVNXYFD5FPY...","$@|\|TO$|-|,Sethu madhav,Akash Thakur,Burger P...","R3F4T5TRYPTMIG,R3DQIEC603E7AY,R1O4Z15FD40PV5,R...","Worked on iPhone 7 and didn’t work on XR,Good ...",Worked on iPhone 7 and didn’t work on iPhone X...,2023-01-06 17:14:45.245901639,Flix Micro Usb Cable For Smartphone (Black),Computers&Accessories,59.00,199.0,4.0,9377.0,"Micro usb cable is 1 meter in length, optimize...",https://m.media-amazon.com/images/I/31qGpf8uzu...,https://www.amazon.in/Flix-Micro-Cable-Smartph...,"WORKED ON IPHONE 7 AND DIDN’T WORK ON XR,GOOD ...",70.351759
59,B09NHVCHS9,"AHIKJUDTVJ4T6DV6IUGFYZ5LXMPA,AE55KTFVNXYFD5FPY...","$@|\|TO$|-|,Sethu madhav,Akash Thakur,Burger P...","R3F4T5TRYPTMIG,R3DQIEC603E7AY,R1O4Z15FD40PV5,R...","Worked on iPhone 7 and didn’t work on XR,Good ...",Worked on iPhone 7 and didn’t work on iPhone X...,2023-01-06 17:14:45.245901639,Flix Micro Usb Cable For Smartphone (Black),Computers&Accessories,59.00,199.0,4.0,9377.0,"Micro usb cable is 1 meter in length, optimize...",https://m.media-amazon.com/images/I/31qGpf8uzu...,https://www.amazon.in/Flix-Micro-Cable-Smartph...,"WORKED ON IPHONE 7 AND DIDN’T WORK ON XR,GOOD ...",70.351759
98,B09NJN8L25,"AHIKJUDTVJ4T6DV6IUGFYZ5LXMPA,AE55KTFVNXYFD5FPY...","$@|\|TO$|-|,Sethu madhav,Akash Thakur,Burger P...","R3F4T5TRYPTMIG,R3DQIEC603E7AY,R1O4Z15FD40PV5,R...","Worked on iPhone 7 and didn’t work on XR,Good ...",Worked on iPhone 7 and didn’t work on iPhone X...,2023-01-11 22:33:26.557377049,FLiX (Beetel USB to Micro USB PVC Data Sync & ...,Computers&Accessories,59.00,199.0,4.0,9378.0,Micro USB charging cable for android phones an...,https://m.media-amazon.com/images/I/31v7NnnAIt...,https://www.amazon.in/FLiX-Charging-480Mbps-De...,"WORKED ON IPHONE 7 AND DIDN’T WORK ON XR,GOOD ...",70.351759
160,B09NKZXMWJ,"AHIKJUDTVJ4T6DV6IUGFYZ5LXMPA,AE55KTFVNXYFD5FPY...","$@|\|TO$|-|,Sethu madhav,Akash Thakur,Burger P...","R3F4T5TRYPTMIG,R3DQIEC603E7AY,R1O4Z15FD40PV5,R...","Worked on iPhone 7 and didn’t work on XR,Good ...",Worked on iPhone 7 and didn’t work on iPhone X...,2023-01-21 03:20:39.344262295,Flix (Beetel) Usb To Type C Pvc Data Sync And ...,Computers&Accessories,139.00,249.0,4.0,9378.0,Durable Pvc Outer Exterior: Pvc Cables Are Ver...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/FLiX-Charging-480Mbps-De...,"WORKED ON IPHONE 7 AND DIDN’T WORK ON XR,GOOD ...",44.176707
258,B0B3N8VG24,"AHIKJUDTVJ4T6DV6IUGFYZ5LXMPA,AE55KTFVNXYFD5FPY...","$@|\|TO$|-|,Sethu madhav,Akash Thakur,Burger P...","R3F4T5TRYPTMIG,R3DQIEC603E7AY,R1O4Z15FD40PV5,R...","Worked on iPhone 7 and didn’t work on XR,Good ...",Worked on iPhone 7 and didn’t work on iPhone X...,2023-02-13 18:13:46.229508196,FLiX (Beetel USB to Type C PVC Data Sync & 15W...,Computers&Accessories,88.00,299.0,4.0,9378.0,FLiX Flow Type C cable offers universal compat...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/FLiX-Charging-480Mbps-An...,"WORKED ON IPHONE 7 AND DIDN’T WORK ON XR,GOOD ...",70.568562
260,B0B3MQXNFB,"AHIKJUDTVJ4T6DV6IUGFYZ5LXMPA,AE55KTFVNXYFD5FPY...","$@|\|TO$|-|,Sethu madhav,Akash Thakur,Burger P...","R3F4T5TRYPTMIG,R3DQIEC603E7AY,R1O4Z15FD40PV5,R...","Worked on iPhone 7 and didn’t work on XR,Good ...",Worked on iPhone 7 and didn’t work on iPhone X...,2023-02-14 06:09:50.163934426,FLiX (Beetel Flow USB to Micro USB PVC Data Sy...,Computers&Accessories,57.89,199.0,4.0,9378.0,FLiX Flow Micro USB cable offers universal com...,https://m.media-amazon.com/images/I/31jSLNakA7...,https://www.amazon.in/FLiX-Charging-480Mbps-An...,"WORKED ON IPHONE 7 AND DIDN’T WORK ON XR,GOOD ...",70.909548
278,B08P9RYPLR,"AHIKJUDTVJ4T6DV6IUGFYZ5LXMPA,AE55KTFVNXYFD5FPY...","$@|\|TO$|-|,Sethu madhav,Akash Thakur,Burger P...","R3F4T5TRYPTMIG,R3DQIEC603E7AY,R1O4Z15FD40PV5,R...","Worked on iPhone 7 and didn’t work on XR,Good ...",Worked on iPhone 7 and didn’t work on iPhone X...,2023-02-18 17:34:25.573770492,FLiX (Beetel) USB to iPhone Lightning Textured...,Computers&Accessories,129.00,249.0,4.0,9378.0,"TPE material|Output port, 1 meter USB cable le...",https://m.media-amazon.com/images/I/31s3DOD2d1...,https://www.amazon.in/FLiX-Beetel-Durable-Ligh...,"WORKED ON IPHONE 7 AND DIDN’T WORK ON XR,GOOD ...",48.192771
335,B08N1WL9XW,"AHIKJUDTVJ4T6DV6IUGFYZ5LXMPA,AE55KTFVNXYFD5FPY...","$@|\|TO$|-|,Sethu madhav,Akash Thakur,Burger P...","R3F4T5TRYPTMIG,R3DQIEC603E7AY,R1O4Z15FD40PV5,R...","Worked on iPhone 7 and didn’t work on XR,Good ...",Worked on iPhone 7 and didn’t work on iPhone X...,2023-03-04 21:42:17.704918033,FLiX (Beetel) 3in1 (Type C|Micro|Iphone Lighte...,Computers&Accessories,182.00,599.0,4.0,9378.0,Proudly Made In India|Blazing Charging - All c...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/FLiX-Textured-charging-L...,"WORKED ON IPHONE 7 AND DIDN’T WORK ON XR,GOOD ...",69.616027
473,B098NS6PVG,"AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,2023-04-04 17:38:21.639344262,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories,199.00,349.0,4.0,43994.0,"Compatible with all Type C enabled devices, be...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...,"A GOOD BRAIDED CABLE FOR YOUR TYPE C DEVICE,GO...",42.979943
474,B098NS6PVG,"AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,2023-04-04 17:38:21.639344262,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories,199.00,349.0,4.0,43993.0,"Compatible with all Type C enabled devices, be...",https://m.media-amazon.com/images/I/31zOsqQOAO...,https://www.amazon.in/Ambrane-Unbreakable-Char...,"A GOOD BRAIDED CABLE FOR YOUR TYPE C DEVICE,GO...",42.979943
475,B098NS6PVG,"AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,2023-04-04 17:38:21.639344262,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories,199.00,349.0,4.0,43994.0,"Compatible with all Type C enabled devices, be...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...,"A GOOD BRAIDED CABLE FOR YOUR TYPE C DEVICE,GO...",42.979943
539,B082LZGK39,"AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,2023-04-16 04:07:52.131147540,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories,199.00,299.0,4.0,43994.0,Universal Compatibility – It is compatible wit...,https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...,"A GOOD BRAIDED CABLE FOR YOUR TYPE C DEVICE,GO...",33.444816
540,B082LZGK39,"AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,2023-04-16 04:07:52.131147540,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories,199.00,299.0,4.0,43994.0,Universal Compatibility – It is compatible wit...,https://m.media-amazon.com/images/I/31kj3q4Sep...,https://www.amazon.in/Ambrane-Unbreakable-Char...,"A GOOD BRAIDED CABLE FOR YOUR TYPE C DEVICE,GO...",33.444816
602,B082LSVT4B,"AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,2023-04-27 20:35:24.590163934,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories,249.00,399.0,4.0,43994.0,"Compatible with all Type C enabled devices, be...",https://m.media-amazon.com/images/I/41d84o5-M-...,https://www.amazon.in/Ambrane-Unbreakable-Char...,"A GOOD BRAIDED CABLE FOR YOUR TYPE C DEVICE,GO...",37.593985
603,B082LSVT4B,"AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,2023-04-27 20:35:24.590163934,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories,249.00,399.0,4.0,43994.0,"Compatible with all Type C enabled devices, be...",https://m.media-amazon.com/images/I/41d84o5-M-...,https://www.amazon.in/Ambrane-Unbreakable-Char...,"A GOOD BRAIDED CABLE FOR YOUR TYPE C DEVICE,GO...",37.593985
613,B09NHVCHS9,"AHIKJUDTVJ4T6DV6IUGFYZ5LXMPA,AE55KTFVNXYFD5FPY...","$@|\|TO$|-|,Sethu madhav,Akash Thakur,Burger P...","R3F4T5TRYPTMIG,R3DQIEC603E7AY,R1O4Z15FD40PV5,R...","Worked on iPhone 7 and didn’t work on XR,Good ...",Worked on iPhone 7 and didn’t work on iPhone X...,2023-04-29 20:19:40.327868852,Flix Micro Usb Cable For Smartphone (Black),Computers&Accessories,59.00,199.0,4.0,9378.0,"Micro usb cable is 1 meter in length, optimize...",https://m.media-amazon.com/images/I/31qGpf8uzu...,https://www.amazon.in/Flix-Micro-Cable-Smartph...,"WORKED ON IPHONE 7 AND DIDN’T WORK ON XR,GOOD ...",70.351759
614,B09NHVCHS9,"AHIKJUDTVJ4T6DV6IUGFYZ5LXMPA,AE55KTFVNXYFD5FPY...","$@|\|TO$|-|,Sethu madhav,Akash Thakur,Burger P...","R3F4T5TRYPTMIG,R3DQIEC603E7AY,R1O4Z15FD40PV5,R...","Worked on iPhone 7 and didn’t work on XR,Good ...",Worked on iPhone 7 and didn’t work on iPhone X...,2023-04-29 20:19:40.327868852,Flix Micro Usb Cable For Smartphone (Black),Computers&Accessories,59.00,199.0,4.0,9377.0,"Micro usb cable is 1 meter in length, optimize...",https://m.media-amazon.com/images/I/31qGpf8uzu...,https://www.amazon.in/Flix-Micro-Cable-Smartph...,"WORKED ON IPHONE 7 AND DIDN’T WORK ON XR,GOOD ...",70.351759
615,B09NHVCHS9,"AHIKJUDTVJ4T6DV6IUGFYZ5LXMPA,AE55KTFVNXYFD5FPY...","$@|\|TO$|-|,Sethu madhav,Akash Thakur,Burger P...","R3F4T5TRYPTMIG,R3DQIEC603E7AY,R1O4Z15FD40PV5,R...","Worked on iPhone 7 and didn’t work on XR,Good ...",Worked on iPhone 7 and didn’t work on iPhone X...,2023-04-29 20:19:40.327868852,Flix Micro Usb Cable For Smartphone (Black),Computers&Accessories,59.00,199.0,4.0,9377.0,"Micro usb cable is 1 meter in length, optimize...",https://m.media-amazon.com/images/I/31qGpf8uzu...,https://www.amazon.in/Flix-Micro-Cable-Smartph...,"WORKED ON IPHONE 7 AND DIDN’T WORK ON XR,GOOD ...",70.351759
625,B09NL4DJ2Z,"AHIKJUDTVJ4T6DV6IUGFYZ5LXMPA,AE55KTFVNXYFD5FPY...","$@|\|TO$|-|,Sethu madhav,Akash Thakur,Burger P...","R3F4T5TRYPTMIG,R3DQIEC603E7AY,R1O4Z15FD40PV5,R...","Worked on iPhone 7 and didn’t work on XR,Good ...",Worked on iPhone 7 and didn’t work on iPhone X...,2023-05-01 20:03:56.065573770,FLiX (Beetel) USB to Type C PVC Data Sync & 2A...,Computers&Accessories,139.00,249.0,4.0,9377.0,Durable Pvc Outer Exterior: Pvc Cables Are Ver...,https://m.media-amazon.com/images/I/31tWzHMz6v...,https://www.amazon.in/Beetel-Smartphone-Chargi...,"WORKED ON IPHONE 7 AND DIDN’T WORK ON XR,GOOD ...",44.176707
798,B098NS6PVG,"AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,2023-06-04 15:36:23.606557376,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories,199.00,349.0,4.0,43994.0,"Compatible with all Type C enabled devices, be...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...,"A GOOD BRAIDED CABLE FOR YOUR TYPE C DEVICE,GO...",42.979943
799,B098NS6PVG,"AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,2023-06-04 15:36:23.606557376,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories,199.00,349.0,4.0,43993.0,"Compatible with all Type C enabled devices, be...",https://m.media-amazon.com/images/I/31zOsqQOAO...,https://www.amazon.in/Ambrane-Unbreakable-Char...,"A GOOD BRAIDED CABLE FOR YOUR TYPE C DEVICE,GO...",42.979943
800,B098NS6PVG,"AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...","ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...","RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...","A Good Braided Cable for Your Type C Device,Go...",I ordered this cable to connect my phone to An...,2023-06-04 15:36:23.606557376,Ambrane Unbreakable 60W / 3A Fast Charging 1.5...,Computers&Accessories,199.00,349.0,4.0,43994.0,"Compatible with all Type C enabled devices, be...",https://m.media-amazon.com/images/W/WEBP_40237...,https://www.amazon.in/Ambrane-Unbreakable-Char...,"A GOOD BRAIDED CABLE FOR YOUR TYPE C DEVICE,GO...",42.979943
943,B09NHVCHS9,"AHIKJUDTVJ4T6DV6IUGFYZ5LXMPA,AE55KTFVNXYFD5FPY...","$@|\|TO$|-|,Sethu madhav,Akash Thakur,Burger P...","R3F4T5TRYPTMIG,R3DQIEC603E7AY,R1O4Z15FD40PV5,R...","Worked on iPhone 7 and didn’t work on XR,Good ...",Worked on iPhone 7 and didn’t work on iPhone X...,2023-06-30 18:09:50.163934426,Flix Micro Usb Cable For Smartphone (Black),Computers&Accessories,59.00,199.0,4.0,9378.0,"Micro usb cable is 1 meter in length, optimize...",https://m.media-amazon.com/images/I/31qGpf8uzu...,https://www.amazon.in/Flix-Micro-Cable-Smartph...,"WORKED ON IPHONE 7 AND DIDN’T WORK ON XR,GOOD ...",70.351759
944,B09NHVCHS9,"AHIKJUDTVJ4T6DV6IUGFYZ5LXMPA,AE55KTFVNXYFD5FPY...","$@|\|TO$|-|,Sethu madhav,Akash Thakur,Burger P...","R3F4T5TRYPTMIG,R3DQIEC603E7AY,R1O4Z15FD40PV5,R...","Worked on iPhone 7 and didn’t work on XR,Good ...",Worked on iPhone 7 and didn’t work on iPhone X...,2023-06-30 18:09:50.163934426,Flix Micro Usb Cable For Smartphone (Black),Computers&Accessories,59.00,199.0,4.0,9377.0,"Micro usb cable is 1 meter in length, optimize...",https://m.media-amazon.com/images/I/31qGpf8uzu...,https://www.amazon.in/Flix-Micro-Cable-Smartph...,"WORKED ON IPHONE 7 AND DIDN’T WORK ON XR,GOOD ...",70.351759

<span style =color:violet>Notice what's happening here?</span>

- We first group data by director and then use `groupby().filter` function.
- **Groups are filtered if they do not satisfy the boolean criterion** specified by the function.
- This is called **Group Based Filtering**.

<span style =color:red>**Note:**</span>
- We are filtering the **groups** here and **not the rows**.
- The result is **not a groupby object** but regular **Pandas DataFrame** with the **filtered groups eliminated**.


## **3. Group-Based Apply**

The <font color="magenta">`.apply()`</font> method allows us to perform **custom operations** on each group, enabling advanced transformations and computations.

### <span style=color:orange> Business Context:</span>

Amazon’s vast e-commerce ecosystem generates complex datasets, including customer orders, product reviews, and sales data, which require customized transformations to derive actionable insights. Using pandas’ .apply() with grouped data enables Amazon to perform tailored computations on subsets, such as calculating custom metrics per product category or user segment. This supports strategic decisions like optimizing pricing, personalizing customer recommendations, or identifying top-performing products, ultimately enhancing customer satisfaction and operational efficiency.

> [Interactive]: Explore how groupby apply runs custom functions on each group step by step before diving into the code:
[GroupBy Apply Visualizer](https://aiml-v-izs.vercel.app/v/az-j9x3r6t1/pd-groupby)

> Select the operation for apply from dropdown

Here are some examples of group-based operations using `.apply()`:

**Example 1: Group-based apply with a custom function**

Here, we group by category and use apply with a custom function that calculates the difference between average actual price and average discounted price. This might help show how much discount each category usually has.

In [ ]:
# Example 1: Group-based apply with a custom function

# Define a custom function to compute average price difference for each group
def avg_price_diff(group):
    # We handle potential missing data
    avg_actual = group['actual_price'].mean()
    avg_discounted = group['discounted_price'].mean()
    return avg_actual - avg_discounted

# Apply this function to each group (category) in df
price_diff_by_category = df.groupby('category').apply(avg_price_diff)

price_diff_by_category

/tmp/ipython-input-3340978438.py:11: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  price_diff_by_category = df.groupby('category').apply(avg_price_diff)

category
Car&Motorbike            1661.000000
Computers&Accessories     740.857453
Electronics              4143.782554
Health&PersonalCare      1001.000000
Home&Kitchen             1857.723325
HomeImprovement           462.000000
MusicalInstruments        709.000000
OfficeProducts             65.686022
Toys&Games                  0.000000
dtype: float64

- **Example 2 using .apply()**


The goal is to compute mean rating, min discounted price, and max discounted price by category. We define a custom function that returns a pd.Series containing these statistics:

In [ ]:
# Example 2 using .apply()

# Define a custom aggregation function
def my_aggregations(group):
    return pd.Series({
        'mean_rating': group['rating'].mean(),
        'min_discounted_price': group['discounted_price'].min(),
        'max_discounted_price': group['discounted_price'].max()
    })

# Apply custom function after grouping by 'category'
stats_by_category = df.groupby('category').apply(my_aggregations)

print(stats_by_category)

                       mean_rating  min_discounted_price  max_discounted_price
category
Car&Motorbike             3.800000                2339.0                2339.0
Computers&Accessories     4.158934                  39.0               37247.0
Electronics               4.090508                  79.0               77990.0
Health&PersonalCare       4.000000                 899.0                 899.0
Home&Kitchen              4.045890                  79.0               42990.0
HomeImprovement           4.250000                 249.0                 425.0
MusicalInstruments        3.900000                 478.0                 798.0
OfficeProducts            4.309677                  50.0                1399.0
Toys&Games                4.300000                 150.0                 150.0

/tmp/ipython-input-1885644465.py:12: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  stats_by_category = df.groupby('category').apply(my_aggregations)

- **Example 3: Creating a new column during groupby apply, then filtering with .loc**

Below is an additional example that creates a new column via a custom function and uses the group keys. Afterward, we use .loc to filter out certain rows based on our newly created column.

In [ ]:
# Example: Creating a new column during groupby apply, then filtering with .loc

# Let's define a custom function to classify reviews by "rating"
def add_review_status(group):
    # Create a new column in each group based on the rating
    group['review_status'] = group['rating'].apply(
        lambda x: 'Good' if x is not None and x > 4.2 else 'Not Good'
    )
    return group

# We group by 'category', and use group_keys=True (this ensures the group labels are preserved)
df_with_status = df.groupby('category', group_keys=True).apply(add_review_status)

df_with_status

/tmp/ipython-input-124281565.py:12: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_with_status = df.groupby('category', group_keys=True).apply(add_review_status)

                            product_id  \
category
Car&Motorbike         1429  B0912WJ87V
Computers&Accessories 0     B07JW9H4J1
                      1     B07JW9H4J1
                      2     B07JW9H4J1
                      3     B098NS6PVG
...                                ...
OfficeProducts        1259  B00S2SEV7K
                      1269  B086Q3QMFS
                      1271  B07LFQLKFZ
                      1272  B00LY17RHI
Toys&Games            1171  B00DJ5N9VK

                                                                      user_id  \
category
Car&Motorbike         1429  AG6W5HESRSDLBX3NCYOOUGFOWERA,AED4U5CF37HVSYPMD...
Computers&Accessories 0     AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...
                      1     AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...
                      2     AG3D6O4STAQKAY2UVGEUV46KN35Q,AHMY5CWJMMK5BJRBB...
                      3     AECPFYFQVRUWC3KGNLJIOREFP5LQ,AGYYVPDD7YG7FYNBX...
...                                                                       ...
OfficeProducts        1259  AFSJUWV2I4CD53EPCRMOQJ3CWR3Q,AGLYAYWTFPPMLELDG...
                      1269  AENWPLS2BHDMH4O6DD7EYV5DOGHQ,AGWEZX7ZMZNEDPVTP...
                      1271  AG23N2Z5CVKFJZ6ZLIYU4NQTDKFA,AG2T5VLGSYCC4K6VI...
                      1272  AE6FSULFZEB65U7FWSETNHLBP5JQ,AGV3YW3GZJTWUP4FC...
Toys&Games            1171  AE5D3EMPETKIA4VU4SZU5UIHXKQA,AFF76KWKCMR6GNPUX...

                                                                    user_name  \
category
Car&Motorbike         1429  Arivazhagan,Ajit,swanand pandit,Venkatesh S.,S...
Computers&Accessories 0     Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...
                      1     Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...
                      2     Manav,Adarsh gupta,Sundeep,S.Sayeed Ahmed,jasp...
                      3     ArdKn,Nirbhay kumar,Sagar Viswanathan,Asp,Plac...
...                                                                       ...
OfficeProducts        1259  Abhay Gupta,vimal rastogi,Sughnesha,Prityush,A...
                      1269  a.john,Sonika sharma,Umadevi,tarun,venkatesh k...
                      1271  Amit  Kumar Chaudhary,Ankita Kakkar,Neelam Cho...
                      1272  Rayees Tigadi,ajay,Tathagata Chakraborty,Rajen...
Toys&Games            1171  Aradhna Aadhya,sonali ghosh,Sam,VGRK,Surfer007...

                                                                    review_id  \
category
Car&Motorbike         1429  R3TOOFPX256D59,R1PR50BDQOEIIO,R392FI4QWXWOX5,R...
Computers&Accessories 0     R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...
                      1     R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...
                      2     R3HXWT0LRP0NMF,R2AJM3LFTLZHFO,R6AQJGUP6P86,R1K...
                      3     RGIQEG07R9HS2,R1SMWZQ86XIN8U,R2J3Y1WL29GWDE,RY...
...                                                                       ...
OfficeProducts        1259  R1QL22IXTM3HYM,R2BCCQQCMW4X56,R8MW9P91PIMJ3,R1...
                      1269  RSVV6T480YK7W,R22DHM4LC4189N,RS51GZQV4URIF,R3K...
                      1271  R2CZ99K13VTGRS,R34J3428JVACPO,R2F41WQEBTUTFF,R...
                      1272  R1KPESOANRAUT2,R2765UCQGUXR8Z,R1MIY4MLC7OEMH,R...
Toys&Games            1171  R39PYNXMLNEIYW,R3AMNR0LJWNAUU,R2P5M80U8OL9OQ,R...

                                                                 review_title  \
category
Car&Motorbike         1429  Liked it,User friendly and effective,Not as pe...
Computers&Accessories 0     Satisfied,Charging is really fast,Value for mo...
                      1     Satisfied,Charging is really fast,Value for mo...
                      2     Satisfied,Charging is really fast,Value for mo...
                      3     A Good Braided Cable for Your Type C Device,Go...
...                                                                       ...
OfficeProducts        1259  Good... 😊,Nice pen but it has some problems.,A...
                      1269  Good product for beginners,Wonderful,Good,Rate...
                      1271  Nice but few Cons (*that you must read*),Smoot...
                      1272  Good Pen at Low Cost,... have been reading abo...
Toys&Games            1171  As this was my 2nd order for same product.2nd ...

                                                               review_content  \
category
Car&Motorbike         1429  As of now its working fine, but don't expect m...
Computers&Accessories 0     Looks durable Charging is fine tooNo complains...
                      1     Looks durable Charging is fine tooNo complains...
                      2     Looks durable Charging is fine tooNo complains...
                      3     I ordered this cable to connect my phone to An...
...                                                                       ...
OfficeProducts        1259  Bahut aacha hai ye pen sach me likhne ke Baad ...
                      1269  Good for learning drawing for kids. MRP of pro...
                      1271  ,Writes smoothly,Nice,The look and feel of the...
                      1272  First of All Delivery of Amazon: It was as spe...
Toys&Games            1171  Torn packing.dekhne me product used lg rha tha...

                                          order_timestamp  \
category
Car&Motorbike         1429  2023-10-15 16:03:56.065573772
Computers&Accessories 0     2023-01-01 00:00:00.000000000
                      1     2023-01-01 00:00:00.000000000
                      2     2023-01-01 00:00:00.000000000
                      3     2023-01-01 05:58:01.967213114
...                                                   ...
OfficeProducts        1259  2023-09-04 21:26:33.442622952
                      1269  2023-09-07 03:08:51.147540984
                      1271  2023-09-07 15:04:55.081967212
                      1272  2023-09-07 21:02:57.049180328
Toys&Games            1171  2023-08-18 17:42:17.704918032

                                                                 product_name  \
category
Car&Motorbike         1429  Reffair AX30 [MAX] Portable Air Purifier for C...
Computers&Accessories 0     Wayona Nylon Braided USB to Lightning Fast Cha...
                      1     Wayona Nylon Braided USB to Lightning Fast Cha...
                      2     Wayona Nylon Braided USB to Lightning Fast Cha...
                      3     Ambrane Unbreakable 60W / 3A Fast Charging 1.5...
...                                                                       ...
OfficeProducts        1259  Pilot Frixion Clicker Roller Pen (Blue), (9000...
                      1269  Classmate Drawing Book - Unruled, 40 Pages, 21...
                      1271  Parker Moments Vector Timecheck Gold Trim Roll...
                      1272      Camlin Elegante Fountain Pen - Black/Blue/Red
Toys&Games            1171  Faber-Castell Connector Pen Set - Pack of 25 (...

                                         category  discounted_price  \
category
Car&Motorbike         1429          Car&Motorbike            2339.0
Computers&Accessories 0     Computers&Accessories             399.0
                      1     Computers&Accessories             399.0
                      2     Computers&Accessories             399.0
                      3     Computers&Accessories             199.0
...                                           ...               ...
OfficeProducts        1259         OfficeProducts              90.0
                      1269         OfficeProducts             120.0
                      1271         OfficeProducts             420.0
                      1272         OfficeProducts             225.0
Toys&Games            1171             Toys&Games             150.0

                            actual_price  rating  rating_count  \
category
Car&Motorbike         1429        4000.0     3.8        1118.0
Computers&Accessories 0           1099.0     4.2       24269.0
                      1           1099.0     4.2       24270.0
                      2           1099.0     4.2       24269.0
                      3            349.0     4.0       43994.0
...                                  ...     ...           ...
OfficeProducts        1259         100.0     4.1        6199.0
                      1269         120.0     4.5        4951.0
                      1271         420.0     4.2        1926.0
                      1272         225.0     4.1        4798.0
Toys&Games            1171         150.0     4.3       15867.0

                                                                about_product  \
category
Car&Motorbike         1429  [NEW LAUNCH - INNOVATIVE DESIGN] EFFICIENT PUR...
Computers&Accessories 0     High Compatibility : Compatible With iPhone 12...
                      1     High Compatibility : Compatible With iPhone 12...
                      2     High Compatibility : Compatible With iPhone 12...
                      3     Compatible with all Type C enabled devices, be...
...                                                                       ...
OfficeProducts        1259  Unique patented thermo-sensitive Frixion Ink|A...
                      1269  The cover design of the notebook is subject to...
                      1271  Mode: Roller ball pen|Pen opening mechanism: C...
                      1272  Handcrafted with Gold plated nib|Brass Cap Chr...
Toys&Games            1171  Simply draw and color or clip these pens toget...

                                                                     img_link  \
category
Car&Motorbike         1429  https://m.media-amazon.com/images/W/WEBP_40237...
Computers&Accessories 0     https://m.media-amazon.com/images/W/WEBP_40237...
                      1     https://m.media-amazon.com/images/I/51UsScvHQN...
                      2     https://m.media-amazon.com/images/W/WEBP_40237...
                      3     https://m.media-amazon.com/images/W/WEBP_40237...
...                                                                       ...
OfficeProducts        1259  https://m.media-amazon.com/images/I/21t8TMvuq6...
                      1269  https://m.media-amazon.com/images/W/WEBP_40237...
                      1271  https://m.media-amazon.com/images/W/WEBP_40237...
                      1272  https://m.media-amazon.com/images/W/WEBP_40237...
Toys&Games            1171  https://m.media-amazon.com/images/I/41rJGx-w9i...

                                                                 product_link  \
category
Car&Motorbike         1429  https://www.amazon.in/Reffair-AX30-MAX-Interna...
Computers&Accessories 0     https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
                      1     https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
                      2     https://www.amazon.in/Wayona-Braided-WN3LG1-Sy...
                      3     https://www.amazon.in/Ambrane-Unbreakable-Char...
...                                                                       ...
OfficeProducts        1259  https://www.amazon.in/Pilot-Frixion-Clicker-Ro...
                      1269  https://www.amazon.in/Classmate-Drawing-Book-U...
                      1271  https://www.amazon.in/Parker-Moments-Vector-Ti...
                      1272  https://www.amazon.in/Camlin-Elegante-Fountain...
Toys&Games            1171  https://www.amazon.in/Faber-Castell-Connector-...

                                                       review_title_uppercase  \
category
Car&Motorbike         1429  LIKED IT,USER FRIENDLY AND EFFECTIVE,NOT AS PE...
Computers&Accessories 0     SATISFIED,CHARGING IS REALLY FAST,VALUE FOR MO...
                      1     SATISFIED,CHARGING IS REALLY FAST,VALUE FOR MO...
                      2     SATISFIED,CHARGING IS REALLY FAST,VALUE FOR MO...
                      3     A GOOD BRAIDED CABLE FOR YOUR TYPE C DEVICE,GO...
...                                                                       ...
OfficeProducts        1259  GOOD... 😊,NICE PEN BUT IT HAS SOME PROBLEMS.,A...
                      1269  GOOD PRODUCT FOR BEGINNERS,WONDERFUL,GOOD,RATE...
                      1271  NICE BUT FEW CONS (*THAT YOU MUST READ*),SMOOT...
                      1272  GOOD PEN AT LOW COST,... HAVE BEEN READING ABO...
Toys&Games            1171  AS THIS WAS MY 2ND ORDER FOR SAME PRODUCT.2ND ...

                            calculated_discount review_status
category
Car&Motorbike         1429            41.525000      Not Good
Computers&Accessories 0               63.694268      Not Good
                      1               63.694268      Not Good
                      2               63.694268      Not Good
                      3               42.979943      Not Good
...                                         ...           ...
OfficeProducts        1259            10.000000      Not Good
                      1269             0.000000          Good
                      1271             0.000000      Not Good
                      1272             0.000000      Not Good
Toys&Games            1171             0.000000          Good

[1724 rows x 19 columns]

<span style=color:red>**Note:**</span>
- Setting `group_keys=True`, keeps the group key in the returned dataset.
- This will be default in future versions of Pandas.
- Keep it as False if want the normal behaviour.

In [ ]:
# Now we can filter rows using .loc based on the newly created column
# For example, let's keep only rows labeled as 'Good'
filtered_df = df_with_status.loc[df_with_status['review_status'] == 'Good']

filtered_df.head(10)

                          product_id  \
category
Computers&Accessories 21  B08DDRGWTJ
                      22  B08DDRGWTJ
                      27  B08CF3D7QR
                      28  B08CF3D7QR
                      29  B08CF3D7QR
                      40  B083342NKJ
                      41  B083342NKJ
                      42  B083342NKJ
                      50  B09C6HXFC1
                      51  B09C6HXFC1

                                                                    user_id  \
category
Computers&Accessories 21  AHW6E5LQ2BDYOIVLAJGDH45J5V5Q,AF74RSGCHPZITVFSZ...
                      22  AHW6E5LQ2BDYOIVLAJGDH45J5V5Q,AF74RSGCHPZITVFSZ...
                      27  AGYLPKPZHVYKKZHOTHCTYVEDAJ4A,AGTTU64JMX722LYCN...
                      28  AGYLPKPZHVYKKZHOTHCTYVEDAJ4A,AGTTU64JMX722LYCN...
                      29  AGYLPKPZHVYKKZHOTHCTYVEDAJ4A,AGTTU64JMX722LYCN...
                      40  AGSGSRTEZBQY64WO2HKQTV7TWFSA,AEYD5HVYAJ23CR6PT...
                      41  AGSGSRTEZBQY64WO2HKQTV7TWFSA,AEYD5HVYAJ23CR6PT...
                      42  AGSGSRTEZBQY64WO2HKQTV7TWFSA,AEYD5HVYAJ23CR6PT...
                      50  AFNYIBWKJLJQKY4BGK77ZOTVMORA,AFCTNNMP2LZLY5466...
                      51  AFNYIBWKJLJQKY4BGK77ZOTVMORA,AFCTNNMP2LZLY5466...

                                                                  user_name  \
category
Computers&Accessories 21  Pavan A H,Jayesh bagad,Shridhar,rajendran,karu...
                      22  Pavan A H,Jayesh bagad,Shridhar,rajendran,karu...
                      27  Tanya,Anu,Akshay,Vishal Sagara Shetty,Swatilek...
                      28  Tanya,Anu,Akshay,Vishal Sagara Shetty,Swatilek...
                      29  Tanya,Anu,Akshay,Vishal Sagara Shetty,Swatilek...
                      40  Birendra ku Dash,Aditya Gupta,Abdulla A N,Deep...
                      41  Birendra ku Dash,Aditya Gupta,Abdulla A N,Deep...
                      42  Birendra ku Dash,Aditya Gupta,Abdulla A N,Deep...
                      50  Prasannavijayaraghavan G.,Preet Sikka,Theeban ...
                      51  Prasannavijayaraghavan G.,Preet Sikka,Theeban ...

                                                                  review_id  \
category
Computers&Accessories 21  R2X090D1YHACKR,R32ZCIH9AFNJ60,R3N57EVVG0EHAF,R...
                      22  R2X090D1YHACKR,R32ZCIH9AFNJ60,R3N57EVVG0EHAF,R...
                      27  R11MQS7WD9C3I0,R2AKH69XQY8BY4,R8GBOLYUN5UP6,R1...
                      28  R11MQS7WD9C3I0,R2AKH69XQY8BY4,R8GBOLYUN5UP6,R1...
                      29  R11MQS7WD9C3I0,R2AKH69XQY8BY4,R8GBOLYUN5UP6,R1...
                      40  R2JPQNKCOE10UK,RQI80JG2WZXNF,R2LYZ4CUWPMUJN,R1...
                      41  R2JPQNKCOE10UK,RQI80JG2WZXNF,R2LYZ4CUWPMUJN,R1...
                      42  R2JPQNKCOE10UK,RQI80JG2WZXNF,R2LYZ4CUWPMUJN,R1...
                      50  R12D1BZF9MU8TN,R32MNCWO5LGFCG,RZU3UK8OZKD6X,R3...
                      51  R12D1BZF9MU8TN,R32MNCWO5LGFCG,RZU3UK8OZKD6X,R3...

                                                               review_title  \
category
Computers&Accessories 21  Worth for money - suitable for Android auto,Go...
                      22  Worth for money - suitable for Android auto,Go...
                      27  Good for fast charge but not for data transfer...
                      28  Good for fast charge but not for data transfer...
                      29  Good for fast charge but not for data transfer...
                      40  Good product,using this product 8months It is ...
                      41  Good product,using this product 8months It is ...
                      42  Good product,using this product 8months It is ...
                      50  Good cable for car,Good substitute for orginal...
                      51  Good cable for car,Good substitute for orginal...

                                                             review_content  \
category
Computers&Accessories 21  Worth for money - suitable for Android auto......
                      22  Worth for money - suitable for Android auto......
                      27  The cable is efficient in fast charging but in...
                      28  The cable is efficient in fast charging but in...
                      29  The cable is efficient in fast charging but in...
                      40  I like it 👍👍,Best charging power . I used this...
                      41  I like it 👍👍,Best charging power . I used this...
                      42  I like it 👍👍,Best charging power . I used this...
                      50  I trust this product! Works well with car play...
                      51  I trust this product! Works well with car play...

                                        order_timestamp  \
category
Computers&Accessories 21  2023-01-02 17:46:13.770491803
                      22  2023-01-02 17:46:13.770491803
                      27  2023-01-03 11:40:19.672131147
                      28  2023-01-03 11:40:19.672131147
                      29  2023-01-03 11:40:19.672131147
                      40  2023-01-04 17:30:29.508196721
                      41  2023-01-04 17:30:29.508196721
                      42  2023-01-04 17:30:29.508196721
                      50  2023-01-05 23:20:39.344262295
                      51  2023-01-05 23:20:39.344262295

                                                               product_name  \
category
Computers&Accessories 21             MI Usb Type-C Cable Smartphone (Black)
                      22             MI Usb Type-C Cable Smartphone (Black)
                      27  Portronics Konnect L POR-1081 Fast Charging 3A...
                      28  Portronics Konnect L POR-1081 Fast Charging 3A...
                      29  Portronics Konnect L POR-1081 Fast Charging 3A...
                      40  MI Braided USB Type-C Cable for Charging Adapt...
                      41  MI Braided USB Type-C Cable for Charging Adapt...
                      42  MI Braided USB Type-C Cable for Charging Adapt...
                      50  Duracell USB Lightning Apple Certified (Mfi) B...
                      51  Duracell USB Lightning Apple Certified (Mfi) B...

                                       category  discounted_price  \
category
Computers&Accessories 21  Computers&Accessories             229.0
                      22  Computers&Accessories             229.0
                      27  Computers&Accessories             154.0
                      28  Computers&Accessories             154.0
                      29  Computers&Accessories             154.0
                      40  Computers&Accessories             349.0
                      41  Computers&Accessories             349.0
                      42  Computers&Accessories             349.0
                      50  Computers&Accessories             970.0
                      51  Computers&Accessories             970.0

                          actual_price  rating  rating_count  \
category
Computers&Accessories 21         299.0     4.3       30411.0
                      22         299.0     4.3       30411.0
                      27         339.0     4.3       13391.0
                      28         339.0     4.3       13391.0
                      29         339.0     4.3       13391.0
                      40         399.0     4.4       18757.0
                      41         399.0     4.4       18757.0
                      42         399.0     4.4       18757.0
                      50        1799.0     4.5         815.0
                      51        1799.0     4.5         815.0

                                                              about_product  \
category
Computers&Accessories 21  1m long Type-C USB Cable|Sturdy and Durable. W...
                      22  1m long Type-C USB Cable|Sturdy and Durable. W...
                      27  [CHARGE & SYNC FUNCTION]- This cable comes wit...
                      28  [CHARGE & SYNC FUNCTION]- This cable comes wit...
                      29  [CHARGE & SYNC FUNCTION]- This cable comes wit...
                      40  1M Long Cable. Usb 2.0 (Type A)|Toughened Join...
                      41  1M Long Cable. Usb 2.0 (Type A)|Toughened Join...
                      42  1M Long Cable. Usb 2.0 (Type A)|Braided Usb Ty...
                      50  Supports Ios Devices With Max Output Up To 2.4...
                      51  Supports Ios Devices With Max Output Up To 2.4...

                                                                   img_link  \
category
Computers&Accessories 21  https://m.media-amazon.com/images/I/31XO-wfGGG...
                      22  https://m.media-amazon.com/images/I/31XO-wfGGG...
                      27  https://m.media-amazon.com/images/I/31dJ+lXJq3...
                      28  https://m.media-amazon.com/images/I/31dJ+lXJq3...
                      29  https://m.media-amazon.com/images/W/WEBP_40237...
                      40  https://m.media-amazon.com/images/W/WEBP_40237...
                      41  https://m.media-amazon.com/images/I/31gaP7qpBN...
                      42  https://m.media-amazon.com/images/I/31gaP7qpBN...
                      50  https://m.media-amazon.com/images/W/WEBP_40237...
                      51  https://m.media-amazon.com/images/I/41TZJiPRRw...

                                                               product_link  \
category
Computers&Accessories 21  https://www.amazon.in/MI-MTCY001IN-USB-Type-C-...
                      22  https://www.amazon.in/MI-MTCY001IN-USB-Type-C-...
                      27  https://www.amazon.in/Portronics-POR-1081-Char...
                      28  https://www.amazon.in/Portronics-POR-1081-Char...
                      29  https://www.amazon.in/Portronics-POR-1081-Char...
                      40  https://www.amazon.in/Mi-Braided-USB-Type-C-Ca...
                      41  https://www.amazon.in/Mi-Braided-USB-Type-C-Ca...
                      42  https://www.amazon.in/Mi-Braided-USB-Type-C-Ca...
                      50  https://www.amazon.in/DURACELL-Lightning-Certi...
                      51  https://www.amazon.in/DURACELL-Lightning-Certi...

                                                     review_title_uppercase  \
category
Computers&Accessories 21  WORTH FOR MONEY - SUITABLE FOR ANDROID AUTO,GO...
                      22  WORTH FOR MONEY - SUITABLE FOR ANDROID AUTO,GO...
                      27  GOOD FOR FAST CHARGE BUT NOT FOR DATA TRANSFER...
                      28  GOOD FOR FAST CHARGE BUT NOT FOR DATA TRANSFER...
                      29  GOOD FOR FAST CHARGE BUT NOT FOR DATA TRANSFER...
                      40  GOOD PRODUCT,USING THIS PRODUCT 8MONTHS IT IS ...
                      41  GOOD PRODUCT,USING THIS PRODUCT 8MONTHS IT IS ...
                      42  GOOD PRODUCT,USING THIS PRODUCT 8MONTHS IT IS ...
                      50  GOOD CABLE FOR CAR,GOOD SUBSTITUTE FOR ORGINAL...
                      51  GOOD CABLE FOR CAR,GOOD SUBSTITUTE FOR ORGINAL...

                          calculated_discount review_status
category
Computers&Accessories 21            23.411371          Good
                      22            23.411371          Good
                      27            54.572271          Good
                      28            54.572271          Good
                      29            54.572271          Good
                      40            12.531328          Good
                      41            12.531328          Good
                      42            12.531328          Good
                      50            46.081156          Good
                      51            46.081156          Good

# Question
You run:
```
df.groupby("Region")["Sales"].mean()
```
Which statement is correct?

# Choices
- [ ] The output must be a DataFrame.
- [x] The output will be a Series indexed by "Region".
- [ ] The output must contain the original index of `df`.
- [ ] GroupBy always returns the same type regardless of aggregation.

Explanation: When selecting a single column before aggregation, the result is a Series. If multiple columns are aggregated, it’s a DataFrame. Subtle but critical difference.

---
Now we will export the `df_with_status` to a csv file and will use the same file in continuation in the next lecture.

In [ ]:
df_with_status.to_csv('exported_df.csv', index=False)
print("DataFrame exported to 'exported_df.csv'")

DataFrame exported to 'exported_df.csv'