<a href="https://colab.research.google.com/github/gautamkr1876/AIML_ClassNotes/blob/main/Data%20Foundation/G-Analyzing%20Sachin%20Tendulkar%27s%20ODI%20Career/Analyzing_Sachin_Tendulkar%27s_ODI_Career.ipynb" target="_blank">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Analyzing Sachin Tendulkar's ODI Career

# Agenda of the lecture

## <span style=color:skyblue>Agenda</span>
- Probability
    - Introduction to the Dataset & Business Context
    - Basic Probability Terminology & Concepts
- Probability Rules & Conditional Probability
- Bayes Theorem

> <span style=color:red>Note:</span> <span style=background-color:blue>[Link for the google colab notebook](https://colab.research.google.com/drive/1tGk7OJ14sZKNwR0faYPB6fIZy_qvwdud?usp=sharing)</span> used in the lecture.

---
# Syllabus Discussion


- We are all learning AIML and specifically Applied AI.
    -  Now we have one more term that is DSML, which consists of NumPy, Pandas, Matplotlib.
    - And then we have probability, distribution, hypothesis testing, and basically.
    - After all of this, we start with machine learning.

- But in Applied AI, things have changed. Here, after your NumPy, Pandas, and Matplotlib, we will have a refresher lecture on probability
    - And then ML, DL, Agent,
    - And once that part is done, we will have the Maths module in a detailed manner.

- <span style="color: violet;">But why did we move from the DSML module to Applied AI?</span>

- <span style="color: violet;">See, as a data scientist, have you seen any change in your current company? Like what they are asking for nowadays?</span>

<span style="background-color: red;color: White;">Student's answer:</span> GenAI, Agentic AI & Gen AI, Work experience with LLMS, Ml(Predictive modelling), Gen AI, MLOPS, langchain langgraph

- Yes, if you see every company is looking for GenAI, they are not asking much about ML, Probability, and all.
    - So, our complete agenda will be related to this.

Let's start with a very interesting module, **Probability**.

- You have a very well-known example of Probability that is Toss a coin and get a head or tail (Probability of head or tail is 1/2)

# Probability Use Cases

- <span style="color: violet;">**When Maggie was banned, did anyone know the reason?**</span>
    - Yes, there is lead present in Maggie, and the amount was greater than the threshold(approx 4.3ppm).
- <span style="color: violet;">But at that time Nestle had almost let's say 4cr packets in their factory. **Did the Govt. check every packet?**</span>
    - No, that's actually not possible for testing 4cr packets.
    - So, they chose random packets, did the testing, and reached a value of 4.3ppm.
    
There are several use cases of probability such as:

## <span style="color: skyblue;">Use Case 1</span>

- Imagine you have a coin and toss it 10 times.
    - The result comes as 6 times head and 4 times tail (H>T).
    - This is in a completely random manner.
    - From 10 samples, we cannot say that is this a unbiased coin.
- To get a biased coin, the heads and tails should be the same number of times.

- Now, Imagine if I toss the same coin for 10,000 times.
    - The result comes as 9000 times head and 1000 times tail (H>T).
    - We can clearly say it is a biased coin.
    - That's how probaility helps us to solve things.

## <span style="color: skyblue;">Use Case 2</span>
- When we type in mobile chat, `How are`...
    - We  may get 3 suggestions:
        - they
        - you
        - him
    - These suggestions changes based on the previous sentence we type.
    - It calculates the most probable word.

## <span style="color: skyblue;">Other Use Cases</span>
- On television, channels show probability of winning of each team during live cricket matches.
- In IRCTC app, we see seat allotment probability.
- Click-through ratio is analyzed in UI designs of websites like Amazon.

So let's start with probability in a business context.

# Introduction to the Dataset & Business Context

### About the Dataset and Business Case

<img src="https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/166/997/original/Screenshot_2025-11-21_161617.png?1763721986" width="900" />

**Dataset:** Sachin Tendulkar ODI Cricket Career 🏏
We are analyzing a dataset containing the ODI (One Day International) cricket stats of Sachin Tendulkar, one of the greatest cricketers of all time. The dataset provides detailed performance metrics across 360 matches of his illustrious career. By studying this data, we can explore and gain insights into:
* Performance Patterns: Runs, strike rate, centuries, boundaries, and other key performance indicators.
* Match Outcomes: The relationship between Sachin's performances and the overall outcomes of matches (win or loss).
* Opposition & Venue Analysis: How performance varies against different opponents and at specific grounds.

**Key Business Objectives:**

* Understanding Winning Patterns: Explore how Sachin’s performance influenced match results.
* Performance Insights: Identify trends in centuries, strike rates, and boundary contributions.
* Strategic Scenarios: Use probability-based analysis to uncover interesting scenarios, such as how often a century correlates with a win.
* Historical Appreciation: Showcase Sachin's impact and consistency in ODI cricket with data-driven insights.

We’ll use this dataset to address a series of probability-related questions, exploring Sachin’s performances across various scenarios. This analysis will demonstrate data manipulation, type conversions, and logical operations.

In [ ]:
!wget https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/101/397/original/Sachin_ODI.csv

--2026-01-14 06:59:04--  https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/101/397/original/Sachin_ODI.csv
Resolving d2beiqkhq929f0.cloudfront.net (d2beiqkhq929f0.cloudfront.net)... 18.238.102.180, 18.238.102.107, 18.238.102.53, ...
Connecting to d2beiqkhq929f0.cloudfront.net (d2beiqkhq929f0.cloudfront.net)|18.238.102.180|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 26440 (26K) [text/plain]
Saving to: ‘Sachin_ODI.csv’

Sachin_ODI.csv      100%[===================>]  25.82K   114KB/s    in 0.2s

2026-01-14 06:59:05 (114 KB/s) - ‘Sachin_ODI.csv’ saved [26440/26440]

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

sachin_data  = pd.read_csv("Sachin_ODI.csv")

sachin_data .head()

,runs,NotOut,mins,bf,fours,sixes,sr,Inns,Opp,Ground,Date,Winner,Won,century
0,13,0,30,15,3,0,86.66,1,New Zealand,Napier,1995-02-16,New Zealand,False,False
1,37,0,75,51,3,1,72.54,2,South Africa,Hamilton,1995-02-18,South Africa,False,False
2,47,0,65,40,7,0,117.50,2,Australia,Dunedin,1995-02-22,India,True,False
3,48,0,37,30,9,1,160.00,2,Bangladesh,Sharjah,1995-04-05,India,True,False
4,4,0,13,9,1,0,44.44,2,Pakistan,Sharjah,1995-04-07,Pakistan,False,False

In [ ]:
sachin_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 360 entries, 0 to 359
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   runs     360 non-null    int64
 1   NotOut   360 non-null    int64
 2   mins     360 non-null    object
 3   bf       360 non-null    int64
 4   fours    360 non-null    int64
 5   sixes    360 non-null    int64
 6   sr       360 non-null    float64
 7   Inns     360 non-null    int64
 8   Opp      360 non-null    object
 9   Ground   360 non-null    object
 10  Date     360 non-null    object
 11  Winner   360 non-null    object
 12  Won      360 non-null    bool
 13  century  360 non-null    bool
dtypes: bool(2), float64(1), int64(6), object(5)
memory usage: 34.6+ KB

# Basic Probability Terminology & Concepts

## <span style=color:skyblue>Experiment, Outcomes, and Sample Space</span>
### Experiment
An experiment is any action or process that generates outcomes.
**Example:** Observing Sachin’s performance in an ODI match is an experiment.

### Outcome
An outcome is a single result of an experiment.
**Example:** Sachin scoring 100 runs in a specific match is one possible outcome.

### Sample Space (S)
The sample space is the set of all possible outcomes of an experiment.
**Example:** For Sachin’s ODI career, the sample space might include all possible scores he could achieve in a match (0, 1, 2, ..., 200+).

In [ ]:
## What are all the distinct run totals Sachin Tendulkar has scored in his ODI career, and how many unique outcomes exist?

# Extract unique scores from the dataset
sample_space = sachin_data['runs'].unique()

# Display the sample space
print("Sample Space (Unique Runs):", sorted(sample_space))
print("Number of Unique Outcomes in the Sample Space:", len(sample_space))

Sample Space (Unique Runs): [np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20), np.int64(21), np.int64(22), np.int64(23), np.int64(24), np.int64(25), np.int64(26), np.int64(27), np.int64(28), np.int64(29), np.int64(30), np.int64(31), np.int64(32), np.int64(33), np.int64(34), np.int64(35), np.int64(36), np.int64(37), np.int64(38), np.int64(39), np.int64(40), np.int64(41), np.int64(42), np.int64(43), np.int64(44), np.int64(45), np.int64(46), np.int64(47), np.int64(48), np.int64(49), np.int64(50), np.int64(51), np.int64(52), np.int64(53), np.int64(54), np.int64(55), np.int64(57), np.int64(60), np.int64(61), np.int64(62), np.int64(63), np.int64(64), np.int64(65), np.int64(67), np.int64(68), np.int64(69), np.int64(70), np.int64(71), np.int64(72), np.int64(74), np.int64(77), np.int64(78), np.int64(79), np.int64(80), np.int64(81), np.int64(82), np.int64(83), np.int64(85), np.int64(86), np.int64(87), np.int64(88), np.int64(89), np.int64(90), np.int64(91), np.int64(93), np.int64(94), np.int64(95), np.int64(96), np.int64(97), np.int64(98), np.int64(99), np.int64(100), np.int64(101), np.int64(102), np.int64(104), np.int64(105), np.int64(110), np.int64(111), np.int64(112), np.int64(113), np.int64(114), np.int64(117), np.int64(118), np.int64(120), np.int64(122), np.int64(123), np.int64(124), np.int64(127), np.int64(128), np.int64(134), np.int64(137), np.int64(138), np.int64(139), np.int64(140), np.int64(141), np.int64(143), np.int64(146), np.int64(152), np.int64(163), np.int64(175), np.int64(186), np.int64(200)]
Number of Unique Outcomes in the Sample Space: 122

### <span style=color:orange>Business Context</span>
A sports analytics company wants to understand a player’s scoring patterns to inform commentary, performance predictions, and fan engagement strategies. By analyzing the full range of possible scores a legendary player like Sachin Tendulkar has achieved in ODIs, the company can design statistical models to assess consistency, risk of dismissal, or likelihood of big scores in future scenarios.

## <span style=color:skyblue>Events</span>
An event is a subset of the sample space. It can contain one or more outcomes.
**Example:**
* Event A: Sachin scores more than 100 runs in a match.
* Event B: Sachin scores exactly 0 runs (a duck).

### Types of Events
1. Mutually Exclusive Events
Events that cannot happen at the same time.
Example: Sachin scoring a century and scoring a duck in the same match.
2. Joint Events
Events that can happen simultaneously.
Example: Sachin scores more than 50 runs, and the match is won by India.
3. Independent Events
Events where the occurrence of one does not affect the other.
Example: The outcome of Sachin’s performance and the weather conditions (assuming no match cancellations).
4. Exhaustive Events
A set of events that covers all possible outcomes in the sample space.
Example:
    * Event A: Sachin scores less than 50 runs.
    * Event B: Sachin scores 50 or more runs.
    * Together, these two events are exhaustive.
    
### <span style=color:orange>Business Context</span>
A sports analytics firm wants to understand and model different types of player performance scenarios to guide strategic decisions, commentary, and fan engagement. By analyzing events—specific outcomes or combinations of outcomes in Sachin Tendulkar’s ODI career—they can quantify probabilities of critical moments, such as scoring a century, getting out for a duck, or contributing to a team victory.

Understanding mutually exclusive, joint, independent, and exhaustive events helps in:

* Identifying high-impact performance scenarios.
* Designing predictive models for match outcomes.
* Enhancing visual storytelling for fan engagement using set-based visualizations of player performance.


## <span style=color:skyblue>Visualizing Events with Set Operations</span>
Probability often uses set theory to describe events. Here are three key operations:

### Intersection (∩):
Matches where both events happen
Example: Matches where Sachin scored more than 50 runs and India won.

In [ ]:
sachin_data.head()

,runs,NotOut,mins,bf,fours,sixes,sr,Inns,Opp,Ground,Date,Winner,Won,century
0,13,0,30,15,3,0,86.66,1,New Zealand,Napier,1995-02-16,New Zealand,False,False
1,37,0,75,51,3,1,72.54,2,South Africa,Hamilton,1995-02-18,South Africa,False,False
2,47,0,65,40,7,0,117.50,2,Australia,Dunedin,1995-02-22,India,True,False
3,48,0,37,30,9,1,160.00,2,Bangladesh,Sharjah,1995-04-05,India,True,False
4,4,0,13,9,1,0,44.44,2,Pakistan,Sharjah,1995-04-07,Pakistan,False,False

In [ ]:
## Which ODI matches did Sachin Tendulkar score more than 50 runs in, and India won, and what were the details of those matches?

# Define events
event_A = sachin_data[sachin_data['runs'] > 50]  # Event A: Scores > 50
event_B = sachin_data[sachin_data['Won'] == True]  # Event B: India wins

# Intersection (A ∩ B)
intersection = pd.merge(event_A, event_B, how='inner')

# Display results
print("Matches where Sachin scored > 50 runs and India won:")
intersection[['Opp', 'Ground', 'runs', 'century']]

Matches where Sachin scored > 50 runs and India won:

             Opp     Ground  runs  century
0      Sri Lanka    Sharjah   112     True
1          Kenya    Cuttack   127     True
2    West Indies    Gwalior    70    False
3       Pakistan    Sharjah   118     True
4       Pakistan    Toronto    89    False
..           ...        ...   ...      ...
68     Sri Lanka    Cuttack    96    False
69  South Africa    Gwalior   200     True
70     Australia  Ahmedabad    53    False
71      Pakistan     Mohali    85    False
72      Pakistan      Dhaka    52    False

[73 rows x 4 columns]

### <span style=color:orange>Business Context</span>
A cricket analytics company wants to identify high-impact matches where a player’s performance directly contributes to team success. By analyzing intersections of events—such as Sachin Tendulkar scoring more than 50 runs and India winning—the company can:

* Highlight matches where Sachin’s performance was pivotal.
* Quantify the correlation between individual contributions and team victories.
* Provide insights for commentators, performance analysts, and fan engagement content.

### Union (∪):
Matches where either event happens
Example: Matches where Sachin scored more than 50 runs or India won.

In [ ]:
## List all ODI matches where either Sachin Tendulkar scored more than 50 runs or India won, along with the match details
# Union (A ∪ B) using concatenation and dropping duplicates
union = pd.concat([event_A, event_B]).drop_duplicates()

# Display results
print("Matches where Sachin scored > 50 runs or India won:")
union[['Opp', 'Ground', 'runs', 'century']]

Matches where Sachin scored > 50 runs or India won:

             Opp   Ground  runs  century
5      Sri Lanka  Sharjah   112     True
10   New Zealand   Nagpur    65    False
12         Kenya  Cuttack   127     True
13   West Indies  Gwalior    70    False
14     Australia   Mumbai    90    False
..           ...      ...   ...      ...
346  West Indies  Chennai     2    False
349    Sri Lanka   Mumbai    18    False
351    Sri Lanka    Perth    48    False
356    Sri Lanka   Hobart    39    False
357    Sri Lanka    Dhaka     6    False

[230 rows x 4 columns]

### <span style=color:orange>Business Context</span>
A sports analytics team wants to identify all impactful matches, either driven by Sachin Tendulkar’s strong performance or by team success. By analyzing the union of events—matches where Sachin scored more than 50 runs or India won—they can:

* Capture a broader set of influential matches for commentary and fan engagement.
* Understand both individual brilliance and team performance.
* Identify matches worth highlighting in performance summaries or predictive models.

### Complement (A'):
Matches where the event does not happen
Example: Matches where Sachin did not score a century.

In [ ]:
# Which ODI matches did Sachin Tendulkar not score a century, and what are the details of those matches?
# Complement (A'): Matches where Sachin did not score a century
event_A_complement = sachin_data[sachin_data['runs'] < 100]  # Not a century

# Display results
print("Matches where Sachin did not score a century:")
event_A_complement[['Opp', 'Ground', 'runs', 'century']]

Matches where Sachin did not score a century:

              Opp    Ground  runs  century
0     New Zealand    Napier    13    False
1    South Africa  Hamilton    37    False
2       Australia   Dunedin    47    False
3      Bangladesh   Sharjah    48    False
4        Pakistan   Sharjah     4    False
..            ...       ...   ...      ...
354     Sri Lanka  Brisbane    22    False
355     Australia    Sydney    14    False
356     Sri Lanka    Hobart    39    False
357     Sri Lanka     Dhaka     6    False
359      Pakistan     Dhaka    52    False

[314 rows x 4 columns]

### <span style=color:orange>Business Context</span>
A cricket analytics team wants to study matches where Sachin Tendulkar did not achieve a milestone, such as a century, to:

* Understand patterns in games where he performed below peak levels.
* Analyze factors that might have influenced lower scores (opposition, venue, match conditions).
* Provide insights for performance improvement strategies, commentary, or predictive modeling.

# Probability Rules

Understanding the fundamental rules of probability helps us compute the likelihood of events systematically. Let’s explore these rules using Sachin Tendulkar’s ODI career data.

## <span style=color:skyblue>Addition Rule</span>
The addition rule calculates the probability of either one event or another happening (the union of events).

### Formula:

`P(A∪B)=P(A)+P(B)−P(A∩B)`

**Example:**

What is the probability that Sachin scored more than 50 runs (Event A) or India won the match (Event B)?

In [ ]:
# What is the probability that Sachin Tendulkar scored more than 50 runs or India won the match in his ODI career?

# Total matches
total_matches = len(sachin_data)

# Event A: Sachin scored > 50 runs
event_A = sachin_data[sachin_data['runs'] > 50]

# Event B: India won the match
event_B = sachin_data[sachin_data['Won'] == True]

# Intersection (A ∩ B): Matches where Sachin scored > 50 runs and India won
intersection = pd.merge(event_A, event_B, how='inner')

# Probabilities
P_A = len(event_A) / total_matches
P_B = len(event_B) / total_matches
P_A_intersection_B = len(intersection) / total_matches

# Applying the addition rule
P_A_union_B = P_A + P_B - P_A_intersection_B

print(f"Probability of scoring > 50 runs or India winning: {P_A_union_B:.4f}")

Probability of scoring > 50 runs or India winning: 0.6389

### <span style=color:orange>Business Context</span>
A sports analytics company wants to quantify the likelihood of key match outcomes involving Sachin Tendulkar’s performance and team success. By calculating probabilities using the addition rule, they can:

* Determine how often Sachin scores above 50 or India wins, helping assess his impact on match outcomes.
* Inform predictive models for match results based on player performance.
* Provide statisticians, commentators, and fans with data-driven insights on performance scenarios.

## <span style=color:skyblue>Multiplication Rule</span>
The multiplication rule calculates the probability of both events happening (intersection of events).

### Formula:

`P(A∩B)=P(A)⋅P(B∣A)`

**Example:**

What is the probability that Sachin scored more than 50 runs (Event A) and India won the match (Event B)?

The probability of India winning depends on whether Sachin scores more than 50 runs.

We cannot directly calculate the joint probability 𝑃 ( 𝐴 ∩ 𝐵 ) without knowing 𝑃 ( 𝐵 ∣ 𝐴 )(the probability of India winning given Sachin's performance).

Without the formula, we'd have to experimentally determine how often India wins when Sachin scores more than 50, which is impractical with real-world data.

In [ ]:
## What is the probability that Sachin Tendulkar scored more than 50 runs and India won the match in his ODI career?
# Event A: Sachin scored > 50 runs
P_A = len(event_A) / total_matches

# Conditional probability: P(B | A)
conditional_data = sachin_data[sachin_data['runs'] > 50]
P_B_given_A = len(conditional_data[conditional_data['Won'] == True]) / len(event_A)

# Applying the multiplication rule
P_A_intersection_B = P_A * P_B_given_A

print(f"Probability of scoring > 50 runs and India winning: {P_A_intersection_B:.4f}")

Probability of scoring > 50 runs and India winning: 0.2028

### <span style=color:orange>Business Context</span>
A cricket analytics team wants to measure the likelihood of joint outcomes involving Sachin Tendulkar’s performance and team success. By applying the multiplication rule, they can:

Determine the probability that Sachin scores more than 50 and India wins, capturing the combined effect of player performance on match results.

Inform predictive modeling for match strategies, player impact analysis, and commentary insights.

Avoid impractical manual counting of joint occurrences across hundreds of matches by using conditional probabilities.


## <span style=color:skyblue>Marginal vs. Joint Probability</span>
* Marginal Probability: Probability of a single event happening (e.g., P(A) or P(B)).
Example: Probability that Sachin scored a century (Event C).
* Joint Probability: Probability of two events happening together (e.g., P(A ∩ B)).
Example: Probability that Sachin scored more than 50 runs and hit at least one six (Event D).

1. When We Can Directly Calculate Joint Probability. We can directly compute 𝑃 ( 𝐴 ∩ 𝐵 ) P(A∩B) when we have historical data or independent events.

Example: Rolling Two Dice (Independent Events) Let A = Getting a 4 on the first die.

Let B = Getting a 6 on the second die.

Since rolling one die does not affect the other, the events are independent:
```
𝑃 ( 𝐴 ∩ 𝐵 )
𝑃 ( 𝐴 ) × 𝑃 ( 𝐵 )
1 6 × 1 6
1 36
```
Here, we can directly multiply because the events are independent.

2. When We Cannot Directly Calculate Joint Probability. If events are dependent, we need extra information about how they influence each other.

Example: Sachin Scoring & India Winning (Dependent Events) If Sachin scores more than 50 runs (A), it increases the chance of India winning (B).

Here, we do not have 𝑃 ( 𝐴 ∩ 𝐵 ) directly.

Instead, we have:
```
𝑃 ( 𝐴 ∩ 𝐵 )
𝑃 ( 𝐴 ) × 𝑃 ( 𝐵 ∣ 𝐴 )
```
We need conditional probability because one event affects the other.

In [ ]:
#What is the marginal probability that Sachin Tendulkar scored a century, and what is the joint probability
# that he scored more than 50 runs and hit at least one six in an ODI match?

# Marginal probability: Sachin scored a century
event_C = sachin_data[sachin_data['century'] == True]
P_C = len(event_C) / total_matches

# Joint probability: Sachin scored > 50 runs and hit at least 1 six
event_D = sachin_data[(sachin_data['runs'] > 50) & (sachin_data['sixes'] > 0)]
P_D = len(event_D) / total_matches

print(f"Marginal Probability of Sachin scoring a century: {P_C:.4f}")
print(f"Joint Probability of scoring > 50 runs and hitting at least 1 six: {P_D:.4f}")

Marginal Probability of Sachin scoring a century: 0.1278
Joint Probability of scoring > 50 runs and hitting at least 1 six: 0.1889

### <span style=color:orange>Business Context</span>
A cricket analytics firm wants to differentiate between single-event probabilities and combined-event probabilities in player performance:
* Marginal probability helps understand the likelihood of individual milestones, e.g., how often Sachin scores a century.
* Joint probability measures the chance of multiple achievements occurring together, e.g., scoring over 50 runs and hitting at least one six.

This analysis is crucial for:
* Performance modeling and predictive analytics.
* Evaluating player consistency and impact in high-stakes situations.
* Designing metrics for commentary, fan engagement, or fantasy cricket platforms.

# Question
A box contains 4 red, 5 blue, and 6 green balls. Two balls are drawn without replacement.
Which of the following statements is always true?

# Choices
- [ ] The probability that both balls are red is equal to the probability that both are green.
- [ ] The probability that both balls are of the same color is higher than the probability that they are of different colors.
- [ ] The probability that one ball is red and the other is blue is the same as the probability that one is blue and the other is green.
- [x] The probability that at least one ball is green is greater than 50%.


Explanation:


* **Option A:**

$$
  P(\text{both red}) = \frac{4}{15} \cdot \frac{3}{14} = \frac{12}{210}.
$$

$$
  P(\text{both green}) = \frac{6}{15} \cdot \frac{5}{14} = \frac{30}{210}.
$$

  Not equal → **False**.


* **Option B:**

$$
  P(\text{same color}) = P(RR) + P(BB) + P(GG)
  = \frac{12 + 20 + 30}{210}
  = \frac{62}{210}.
$$

$$
  P(\text{different}) = 1 - \frac{62}{210} = \frac{148}{210}.
$$

  Different color > Same color → **False**.


* **Option C:**

$$
  P(RB) = \frac{4}{15} \cdot \frac{5}{14} + \frac{5}{15} \cdot \frac{4}{14}
  = \frac{40}{210}.
$$

$$
  P(BG) = \frac{5}{15} \cdot \frac{6}{14} + \frac{6}{15} \cdot \frac{5}{14}
  = \frac{60}{210}.
$$

  Not equal → **False**.


* **Option D:**

$$
  P(\text{at least one green}) = 1 - P(\text{no green}).
$$

$$
  P(\text{no green}) = \frac{9}{15} \cdot \frac{8}{14} = \frac{72}{210}.
$$

$$
  P(\ge 1\ \text{green}) = 1 - \frac{72}{210}
  = \frac{138}{210} \approx 65.7% > 50%.
$$

  → **True ✅**

# Question
In a college:
- 45% of students like Mathematics (M),
- 40% like Physics (P),
- 20% like both Mathematics and Physics.


A student is chosen at random. Which of the following statements is true?

# Choices
- [ ] The probability that the student likes at least one of the two subjects is 85%.
- [ ] The probability that the student likes exactly one subject is 65%.
- [x] The probability that the student likes neither subject is 35%.
- [ ] The probability that the student likes both subjects is equal to the probability that they like neither.

Explanation:


We use the formula:

$$
P(M \cup P) = P(M) + P(P) - P(M \cap P)
$$

$$
= 0.45 + 0.40 - 0.20 = 0.65
$$

So, **probability of liking at least one subject = 65% (not 85%)**.

## <span style=color:skyblue>Conditional Probability</span>
Conditional probability calculates the likelihood of an event given that another event has already occurred.

### Formula:

<img src="https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/167/012/original/Screenshot_2025-11-21_164308.png?1763723598" width="300" />

Example:

Given that Sachin scored more than 50 runs (Event A), what is the probability that he scored a century (Event C)?

In [ ]:
## Given that Sachin Tendulkar scored more than 50 runs in an ODI match, what is the probability that he went on to score a century?

# Event A: Sachin scored > 50 runs
event_A = sachin_data[sachin_data['runs'] > 50]

# Event C: Sachin scored a century
event_C_given_A = event_A[event_A['century'] == True]

# Conditional probability
P_C_given_A = len(event_C_given_A) / len(event_A)

print(f"Probability of scoring a century given runs > 50: {P_C_given_A:.4f}")

Probability of scoring a century given runs > 50: 0.3866

### <span style=color:orange>Business Context</span>
A cricket analytics team wants to evaluate the likelihood of milestone achievements given a prior performance. By calculating conditional probabilities, they can:

* Assess the probability that Sachin Tendulkar scored a century, given he had already scored more than 50 runs in a match.
* Identify scenarios where high scores are likely to convert into major milestones.
* Inform predictive models, commentary insights, and performance strategy evaluations.

# Question
A fair coin is tossed twice. Let:

$A$ = event that the first toss is Heads.
$B$ = event that the second toss is Heads.


Which of the following statements is WRONG?

# Choices
- [ ] $P(A)=P(B)=0.5$
- [ ] $P(A∩B)=P(A)⋅P(B)$
- [x] $P(A∪B)=P(A)+P(B)$
- [ ] $P(A^c)=1−P(A)$


Explanation:

- **A) True:** Probability of first toss being heads = 0.5, same for second toss.

- **B) True:** Events \( A \) and \( B \) are independent.

$$
  P(A \cap B) = P(A) \cdot P(B) = 0.5 \times 0.5 = 0.25
$$

- **C) Wrong:** They are **not disjoint** (both tosses can be heads).

  **Correct formula:**

$$
  P(A \cup B) = P(A) + P(B) - P(A \cap B) = 0.5 + 0.5 - 0.25 = 0.75
$$

So simply adding gives 1.0 → incorrect.

- **D) True:** Complement rule always holds.

# Question
A box has 4 red and 6 blue balls. If one ball is drawn and it is red, what is the probability that the next ball drawn (without replacement) is also red?
# Choices
- [x] $\frac{3}{9}=\frac{1}{3}$
- [ ] $\frac{4}{10}=0.4$
- [ ] $\frac{6}{9}=\frac{2}{3}$
- [ ] $\frac{5}{9}$

# Bayes' Theorem

Bayes' Theorem is a cornerstone of probability theory that helps us revise probabilities based on new evidence. It enables us to calculate conditional probabilities when the reverse probability and other relevant information are known.

## <span style=color:skyblue>Formula for Bayes' Theorem</span>
The formula for Bayes' Theorem is:
<img src="https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/167/013/original/Screenshot_2025-11-21_164529.png?1763723744" width="300" />

Where:

* P(A∣B): Probability of A occurring given that B has occurred (posterior).
* P(B∣A): Probability of B occurring given that A has occurred (likelihood).
* P(A): Probability of A occurring (prior).
* P(B): Probability of B occurring (evidence).

## <span style=color:skyblue>Intuition Behind Bayes' Theorem</span>
**Example:**
In Sachin’s dataset:
* Event A: Sachin scores a century.
* Event B: Sachin batted first.

We want to compute P(A∣B):

What is the probability that Sachin scores a century, given he batted first?

In [ ]:
## Given that Sachin Tendulkar batted first in an ODI match, what is the probability that he scored a century?

# Define the events
event_A = sachin_data[sachin_data['century'] == True]  # Event A: Scored a century
event_B = sachin_data[sachin_data['Inns'] == 1]        # Event B: Batted first

# Total matches
total_matches = len(sachin_data)

# Probabilities
P_A = len(event_A) / total_matches  # Prior probability of scoring a century
P_B = len(event_B) / total_matches  # Probability of batting first
P_B_given_A = len(event_A[event_A['Inns'] == 1]) / len(event_A)  # Likelihood

# Bayes' Theorem
P_A_given_B = (P_B_given_A * P_A) / P_B

print(f"Probability of scoring a century given Sachin batted first: {P_A_given_B:.4f}")

Probability of scoring a century given Sachin batted first: 0.1765

### <span style=color:orange>Business Context</span>
A cricket analytics team wants to revise probabilities based on new information to gain deeper insights into player performance. By applying Bayes’ Theorem, they can:

* Compute the probability that Sachin Tendulkar scores a century given he batted first, updating prior expectations based on observed match conditions.
* Understand how match circumstances (like batting order) influence milestone achievements.
* Support predictive modeling, strategy analysis, and commentary by incorporating conditional insights.

Bayes’ Theorem allows the team to combine historical performance data with contextual information for more accurate probability estimates.

## Real-Life Relevance
Bayes' Theorem is widely used in:

* **Spam Detection:** Classifying emails as spam or not based on keywords.
* **Medical Testing:** Revising the probability of having a disease based on test results.
* **Sports Analytics:** Understanding player performance under specific conditions.

## <span style=color:skyblue>Simple Tree Diagram Approach (Optional)</span>
**A tree diagram** can help visualize the probabilities involved in Bayes' Theorem.

**Example:** Using Tree Diagram Data for Complex Joint Probabilities

What is the probability of Sachin scoring between 50 and 100 runs and India winning, considering the batting order?

<img src="https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/167/016/original/Screenshot_2024-12-30_113248.png?1763724033" width="700" />

<span style="background-color: red;color: White;">Instructor Note:</span> Encourage students to read Post Read : Combinatorics & Additional Probability Methods. Provide a practical example of its application to demonstrate its relevance and importance, motivating them to explore the topic further.

# Question
In a factory, 60% of the workers are skilled and 40% are unskilled.
- A skilled worker has a 90% chance of producing a non-defective item.
- An unskilled worker has a 60% chance of producing a non-defective item.

An item is chosen at random and is found to be defective. Which of the following statements is true?


# Choices
- [x] The probability that it was made by an unskilled worker is greater than the probability that it was made by a skilled worker.
- [ ] The probability that it was made by a skilled worker is 60%.
- [ ] The probability that it was made by an unskilled worker is 40%.
- [ ] Skilled and unskilled workers are equally likely, given the item is defective.

Explanation:


We need $P(\text{Unskilled} \mid \text{Defective})$.

* $P(\text{Defective} \mid \text{Skilled}) = 1 - 0.9 = 0.1$
* $P(\text{Defective} \mid \text{Unskilled}) = 1 - 0.6 = 0.4$

Now apply **Bayes’ Theorem**:

$$
P(\text{Skilled} \mid \text{Defective})=
\frac{P(\text{Skilled}) \cdot P(\text{Def} \mid \text{Skilled})}{P(\text{Def})}
$$

where

$$
P(\text{Def})=
(0.6 \cdot 0.1) + (0.4 \cdot 0.4)
=0.06 + 0.16
=0.22
$$

So:

$$
P(\text{Skilled} \mid \text{Def})=\frac{0.6 \cdot 0.1}{0.22}=
\frac{0.06}{0.22}
\approx 27.27%
$$

$$
P(\text{Unskilled} \mid \text{Def})
\frac{0.4 \cdot 0.4}{0.22}
\frac{0.16}{0.22}
\approx 72.73%
$$

Thus, **defective items are much more likely to come from unskilled workers → A is correct.**